In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("new_database.csv", low_memory=False)
df.shape

(8370, 45)

In [3]:
df = df.drop(['jobma_functional', 'jobma_catcher_company','jobma_catcher_indus', 'subscription_type', 'premium_storage', 'id', 'apply_mode', 'jobma_catcher_creation'], axis=1)
df.shape

(8370, 37)

In [4]:
df.nunique()

catcher_id                  5529
jobma_catcher_title            9
jobma_catcher_otype            7
jobma_catcher_status           3
jobma_catcher_type             2
is_premium                     2
jobma_verified                 2
subscription_status            3
sub_user                      62
per_sub_user                   9
live_interview_credit         22
pre_recorded_credit           29
ai_live_interview_credit       2
interview_cost_type            2
referral_credit                6
company_size                   5
ai_live_interview              2
days_since_creation         1078
confirmed                      2
number_of_logins               6
credit_amount                 39
wallet_amount                714
plan_type                      2
is_unlimited                   2
trial_account_type             2
billing_cycle_status           2
subscription_amount          344
credit_given                  37
currency_val                  39
times_of_subscription         37
kits_count                    55
position_created              62
number_of_invitations        126
pitchers_counts               89
def_interview_counts          94
interview_counts              27
ai_interview_counts            4
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8370 entries, 0 to 8369
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   catcher_id                8370 non-null   int64
 1   jobma_catcher_title       8370 non-null   int64
 2   jobma_catcher_otype       8370 non-null   object
 3   jobma_catcher_status      8370 non-null   int64
 4   jobma_catcher_type        8370 non-null   int64
 5   is_premium                8370 non-null   int64
 6   jobma_verified            8370 non-null   int64
 7   subscription_status       8370 non-null   int64
 8   sub_user                  8370 non-null   int64
 9   per_sub_user              8370 non-null   object
 10  live_interview_credit     8370 non-null   float64
 11  pre_recorded_credit       8370 non-null   float64
 12  ai_live_interview_credit  8370 non-null   float64
 13  interview_cost_type       8370 non-null   int64
 14  referral_credit           8370 non-null   int64
 15  company_size              8370 non-null   object
 16  ai_live_interview         8370 non-null   int64
 17  days_since_creation       8370 non-null   float64
 18  confirmed                 8370 non-null   int64
 19  number_of_logins          8370 non-null   int64
 20  credit_amount             460 non-null    float64
 21  wallet_amount             8370 non-null   float64
 22  plan_type                 8362 non-null   float64
 23  is_unlimited              8268 non-null   float64
 24  trial_account_type        7958 non-null   float64
 25  billing_cycle_status      8370 non-null   int64
 26  subscription_amount       8370 non-null   float64
 27  credit_given              8370 non-null   int64
 28  currency_val              8370 non-null   float64
 29  times_of_subscription     8370 non-null   int64
 30  kits_count                1954 non-null   float64
 31  position_created          1926 non-null   float64
 32  number_of_invitations     1676 non-null   float64
 33  pitchers_counts           1539 non-null   float64
 34  def_interview_counts      1499 non-null   float64
 35  interview_counts          1499 non-null   float64
 36  ai_interview_counts       1499 non-null   float64
dtypes: float64(18), int64(16), object(3)
memory usage: 2.4+ MB

In [6]:
df.isna().sum()

catcher_id                     0
jobma_catcher_title            0
jobma_catcher_otype            0
jobma_catcher_status           0
jobma_catcher_type             0
is_premium                     0
jobma_verified                 0
subscription_status            0
sub_user                       0
per_sub_user                   0
live_interview_credit          0
pre_recorded_credit            0
ai_live_interview_credit       0
interview_cost_type            0
referral_credit                0
company_size                   0
ai_live_interview              0
days_since_creation            0
confirmed                      0
number_of_logins               0
credit_amount               7910
wallet_amount                  0
plan_type                      8
is_unlimited                 102
trial_account_type           412
billing_cycle_status           0
subscription_amount            0
credit_given                   0
currency_val                   0
times_of_subscription          0
kits_count                  6416
position_created            6444
number_of_invitations       6694
pitchers_counts             6831
def_interview_counts        6871
interview_counts            6871
ai_interview_counts         6871
dtype: int64

In [7]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,8360,8361,8362,8363,8364,8365,8366,8367,8368,8369
catcher_id,92,92,92,92,92,92,92,92,106,124,...,9313,9315,9315,9315,9315,9319,9365,9405,9413,9445
jobma_catcher_title,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,1,4,0,1,0,1
jobma_catcher_otype,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
jobma_catcher_status,1,1,1,1,1,1,1,1,-1,1,...,1,1,1,1,1,1,1,1,1,1
jobma_catcher_type,1,1,1,1,1,1,1,1,0,0,...,1,1,1,1,1,1,1,1,1,1
is_premium,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,0
jobma_verified,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
subscription_status,2,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
sub_user,999,999,999,999,999,999,999,999,999,999,...,1,999,999,999,999,999,21,999,10,10
per_sub_user,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
live_interview_credit,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0
pre_recorded_credit,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,9.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0
ai_live_interview_credit,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
interview_cost_type,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,1,0,0
referral_credit,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
company_size,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,...,500-1000,More than 1000,More than 1000,More than 1000,More than 1000,1-25,26-100,1-25,101-500,1-25
ai_live_interview,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
days_since_creation,3066.0,3066.0,3066.0,3066.0,3066.0,3066.0,3066.0,3066.0,4511.0,4169.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
confirmed,1,1,1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,1,1,1,1
number_of_logins,1,1,1,1,1,1,1,1,1,1,...,1,2,2,2,2,1,1,1,1,3
credit_amount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wallet_amount,34.0,34.0,34.0,34.0,3.0,3.0,3.0,3.0,0.0,0.0,...,0.0,500000.0,500000.0,500000.0,500000.0,500000.0,137.0,500000.0,15000.0,150.0
plan_type,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
is_unlimited,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
trial_account_type,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
billing_cycle_status,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
subscription_amount,0.0,0.0,199.0,199.0,0.0,0.0,199.0,199.0,0.0,0.0,...,50.0,10000.0,10000.0,10000.0,10000.0,0.0,50.0,0.0,150.0,0.0
credit_given,0,0,0,0,0,0,0,0,0,0,...,50,0,0,0,0,0,50,0,150,150
currency_val,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
times_of_subscription,2,2,2,2,2,2,2,2,1,1,...,1,1,1,1,1,1,1,1,1,1
kits_count,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,...,1.0,10.0,10.0,10.0,10.0,1.0,NaN,NaN,1.0,NaN
position_created,825.0,825.0,825.0,825.0,825.0,825.0,825.0,825.0,NaN,1.0,...,NaN,18.0,18.0,18.0,18.0,400.0,4.0,NaN,2.0,NaN
number_of_invitations,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,NaN,NaN,...,1.0,152.0,152.0,152.0,152.0,1.0,25.0,NaN,3.0,NaN
pitchers_counts,17640.0,17640.0,17640.0,17640.0,17640.0,17640.0,17640.0,17640.0,NaN,3.0,...,NaN,41.0,41.0,41.0,41.0,1.0,5.0,NaN,NaN,NaN
def_interview_counts,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,NaN,NaN,...,NaN,51.0,51.0,51.0,51.0,1.0,7.0,NaN,NaN,NaN
interview_counts,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,...,NaN,6.0,6.0,6.0,6.0,0.0,0.0,NaN,NaN,NaN
ai_interview_counts,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [8]:
df.isna().sum()

catcher_id                     0
jobma_catcher_title            0
jobma_catcher_otype            0
jobma_catcher_status           0
jobma_catcher_type             0
is_premium                     0
jobma_verified                 0
subscription_status            0
sub_user                       0
per_sub_user                   0
live_interview_credit          0
pre_recorded_credit            0
ai_live_interview_credit       0
interview_cost_type            0
referral_credit                0
company_size                   0
ai_live_interview              0
days_since_creation            0
confirmed                      0
number_of_logins               0
credit_amount               7910
wallet_amount                  0
plan_type                      8
is_unlimited                 102
trial_account_type           412
billing_cycle_status           0
subscription_amount            0
credit_given                   0
currency_val                   0
times_of_subscription          0
kits_count                  6416
position_created            6444
number_of_invitations       6694
pitchers_counts             6831
def_interview_counts        6871
interview_counts            6871
ai_interview_counts         6871
dtype: int64

In [9]:
fill_values = {col: "Unknown" if df[col].dtype == 'object' else 0 for col in df.columns}
df = df.fillna(fill_values)

In [10]:
df.isna().sum()

catcher_id                  0
jobma_catcher_title         0
jobma_catcher_otype         0
jobma_catcher_status        0
jobma_catcher_type          0
is_premium                  0
jobma_verified              0
subscription_status         0
sub_user                    0
per_sub_user                0
live_interview_credit       0
pre_recorded_credit         0
ai_live_interview_credit    0
interview_cost_type         0
referral_credit             0
company_size                0
ai_live_interview           0
days_since_creation         0
confirmed                   0
number_of_logins            0
credit_amount               0
wallet_amount               0
plan_type                   0
is_unlimited                0
trial_account_type          0
billing_cycle_status        0
subscription_amount         0
credit_given                0
currency_val                0
times_of_subscription       0
kits_count                  0
position_created            0
number_of_invitations       0
pitchers_counts             0
def_interview_counts        0
interview_counts            0
ai_interview_counts         0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8370 entries, 0 to 8369
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   catcher_id                8370 non-null   int64
 1   jobma_catcher_title       8370 non-null   int64
 2   jobma_catcher_otype       8370 non-null   object
 3   jobma_catcher_status      8370 non-null   int64
 4   jobma_catcher_type        8370 non-null   int64
 5   is_premium                8370 non-null   int64
 6   jobma_verified            8370 non-null   int64
 7   subscription_status       8370 non-null   int64
 8   sub_user                  8370 non-null   int64
 9   per_sub_user              8370 non-null   object
 10  live_interview_credit     8370 non-null   float64
 11  pre_recorded_credit       8370 non-null   float64
 12  ai_live_interview_credit  8370 non-null   float64
 13  interview_cost_type       8370 non-null   int64
 14  referral_credit           8370 non-null   int64
 15  company_size              8370 non-null   object
 16  ai_live_interview         8370 non-null   int64
 17  days_since_creation       8370 non-null   float64
 18  confirmed                 8370 non-null   int64
 19  number_of_logins          8370 non-null   int64
 20  credit_amount             8370 non-null   float64
 21  wallet_amount             8370 non-null   float64
 22  plan_type                 8370 non-null   float64
 23  is_unlimited              8370 non-null   float64
 24  trial_account_type        8370 non-null   float64
 25  billing_cycle_status      8370 non-null   int64
 26  subscription_amount       8370 non-null   float64
 27  credit_given              8370 non-null   int64
 28  currency_val              8370 non-null   float64
 29  times_of_subscription     8370 non-null   int64
 30  kits_count                8370 non-null   float64
 31  position_created          8370 non-null   float64
 32  number_of_invitations     8370 non-null   float64
 33  pitchers_counts           8370 non-null   float64
 34  def_interview_counts      8370 non-null   float64
 35  interview_counts          8370 non-null   float64
 36  ai_interview_counts       8370 non-null   float64
dtypes: float64(18), int64(16), object(3)
memory usage: 2.4+ MB

In [12]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,8360,8361,8362,8363,8364,8365,8366,8367,8368,8369
catcher_id,92,92,92,92,92,92,92,92,106,124,...,9313,9315,9315,9315,9315,9319,9365,9405,9413,9445
jobma_catcher_title,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,1,4,0,1,0,1
jobma_catcher_otype,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
jobma_catcher_status,1,1,1,1,1,1,1,1,-1,1,...,1,1,1,1,1,1,1,1,1,1
jobma_catcher_type,1,1,1,1,1,1,1,1,0,0,...,1,1,1,1,1,1,1,1,1,1
is_premium,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,0
jobma_verified,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
subscription_status,2,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
sub_user,999,999,999,999,999,999,999,999,999,999,...,1,999,999,999,999,999,21,999,10,10
per_sub_user,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
live_interview_credit,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0
pre_recorded_credit,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,9.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0
ai_live_interview_credit,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
interview_cost_type,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,1,0,0
referral_credit,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
company_size,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,...,500-1000,More than 1000,More than 1000,More than 1000,More than 1000,1-25,26-100,1-25,101-500,1-25
ai_live_interview,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
days_since_creation,3066.0,3066.0,3066.0,3066.0,3066.0,3066.0,3066.0,3066.0,4511.0,4169.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
confirmed,1,1,1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,1,1,1,1
number_of_logins,1,1,1,1,1,1,1,1,1,1,...,1,2,2,2,2,1,1,1,1,3
credit_amount,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wallet_amount,34.0,34.0,34.0,34.0,3.0,3.0,3.0,3.0,0.0,0.0,...,0.0,500000.0,500000.0,500000.0,500000.0,500000.0,137.0,500000.0,15000.0,150.0
plan_type,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
is_unlimited,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
trial_account_type,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
billing_cycle_status,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
subscription_amount,0.0,0.0,199.0,199.0,0.0,0.0,199.0,199.0,0.0,0.0,...,50.0,10000.0,10000.0,10000.0,10000.0,0.0,50.0,0.0,150.0,0.0
credit_given,0,0,0,0,0,0,0,0,0,0,...,50,0,0,0,0,0,50,0,150,150
currency_val,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
times_of_subscription,2,2,2,2,2,2,2,2,1,1,...,1,1,1,1,1,1,1,1,1,1
kits_count,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,1.0,10.0,10.0,10.0,10.0,1.0,0.0,0.0,1.0,0.0
position_created,825.0,825.0,825.0,825.0,825.0,825.0,825.0,825.0,0.0,1.0,...,0.0,18.0,18.0,18.0,18.0,400.0,4.0,0.0,2.0,0.0
number_of_invitations,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,0.0,0.0,...,1.0,152.0,152.0,152.0,152.0,1.0,25.0,0.0,3.0,0.0
pitchers_counts,17640.0,17640.0,17640.0,17640.0,17640.0,17640.0,17640.0,17640.0,0.0,3.0,...,0.0,41.0,41.0,41.0,41.0,1.0,5.0,0.0,0.0,0.0
def_interview_counts,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.0,0.0,...,0.0,51.0,51.0,51.0,51.0,1.0,7.0,0.0,0.0,0.0
interview_counts,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,...,0.0,6.0,6.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0
ai_interview_counts,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
df

,catcher_id,jobma_catcher_title,jobma_catcher_otype,jobma_catcher_status,jobma_catcher_type,is_premium,jobma_verified,subscription_status,sub_user,per_sub_user,...,credit_given,currency_val,times_of_subscription,kits_count,position_created,number_of_invitations,pitchers_counts,def_interview_counts,interview_counts,ai_interview_counts
0,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
1,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
2,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
3,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
4,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8365,9319,4,1,1,1,0,1,1,999,100,...,0,1.0,1,1.0,400.0,1.0,1.0,1.0,0.0,0.0
8366,9365,0,1,1,1,1,1,1,21,100,...,50,1.0,1,0.0,4.0,25.0,5.0,7.0,0.0,0.0
8367,9405,1,1,1,1,0,1,1,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8368,9413,0,1,1,1,0,1,1,10,100,...,150,1.0,1,1.0,2.0,3.0,0.0,0.0,0.0,0.0
8369,9445,1,1,1,1,0,1,1,10,100,...,150,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
df.shape

(8370, 37)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8370 entries, 0 to 8369
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   catcher_id                8370 non-null   int64
 1   jobma_catcher_title       8370 non-null   int64
 2   jobma_catcher_otype       8370 non-null   object
 3   jobma_catcher_status      8370 non-null   int64
 4   jobma_catcher_type        8370 non-null   int64
 5   is_premium                8370 non-null   int64
 6   jobma_verified            8370 non-null   int64
 7   subscription_status       8370 non-null   int64
 8   sub_user                  8370 non-null   int64
 9   per_sub_user              8370 non-null   object
 10  live_interview_credit     8370 non-null   float64
 11  pre_recorded_credit       8370 non-null   float64
 12  ai_live_interview_credit  8370 non-null   float64
 13  interview_cost_type       8370 non-null   int64
 14  referral_credit           8370 non-null   int64
 15  company_size              8370 non-null   object
 16  ai_live_interview         8370 non-null   int64
 17  days_since_creation       8370 non-null   float64
 18  confirmed                 8370 non-null   int64
 19  number_of_logins          8370 non-null   int64
 20  credit_amount             8370 non-null   float64
 21  wallet_amount             8370 non-null   float64
 22  plan_type                 8370 non-null   float64
 23  is_unlimited              8370 non-null   float64
 24  trial_account_type        8370 non-null   float64
 25  billing_cycle_status      8370 non-null   int64
 26  subscription_amount       8370 non-null   float64
 27  credit_given              8370 non-null   int64
 28  currency_val              8370 non-null   float64
 29  times_of_subscription     8370 non-null   int64
 30  kits_count                8370 non-null   float64
 31  position_created          8370 non-null   float64
 32  number_of_invitations     8370 non-null   float64
 33  pitchers_counts           8370 non-null   float64
 34  def_interview_counts      8370 non-null   float64
 35  interview_counts          8370 non-null   float64
 36  ai_interview_counts       8370 non-null   float64
dtypes: float64(18), int64(16), object(3)
memory usage: 2.4+ MB

In [16]:
df.nunique()

catcher_id                  5529
jobma_catcher_title            9
jobma_catcher_otype            7
jobma_catcher_status           3
jobma_catcher_type             2
is_premium                     2
jobma_verified                 2
subscription_status            3
sub_user                      62
per_sub_user                   9
live_interview_credit         22
pre_recorded_credit           29
ai_live_interview_credit       2
interview_cost_type            2
referral_credit                6
company_size                   5
ai_live_interview              2
days_since_creation         1078
confirmed                      2
number_of_logins               6
credit_amount                 39
wallet_amount                714
plan_type                      2
is_unlimited                   2
trial_account_type             2
billing_cycle_status           2
subscription_amount          344
credit_given                  37
currency_val                  39
times_of_subscription         37
kits_count                    56
position_created              63
number_of_invitations        127
pitchers_counts               90
def_interview_counts          94
interview_counts              27
ai_interview_counts            4
dtype: int64

In [17]:
object_df = df.select_dtypes(include=['object'])
object_df.shape

(8370, 3)

In [18]:
object_df.nunique()

jobma_catcher_otype    7
per_sub_user           9
company_size           5
dtype: int64

In [19]:
object_df.T

,0,1,2,3,4,5,6,7,8,9,...,8360,8361,8362,8363,8364,8365,8366,8367,8368,8369
jobma_catcher_otype,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
per_sub_user,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
company_size,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,...,500-1000,More than 1000,More than 1000,More than 1000,More than 1000,1-25,26-100,1-25,101-500,1-25

In [20]:
object_df['jobma_catcher_otype'].value_counts()

jobma_catcher_otype
1                  7916
2                   318
Employer            101
Recruiting Firm      28
Ad Agency             5
101                   1
18                    1
Name: count, dtype: int64

In [21]:
object_df['per_sub_user'].unique()

array(['100', '12000', '10000', '90', '500', '80', '60', '["60","100"]',
       '["10000","100"]'], dtype=object)

In [22]:
object_df['company_size'].unique()

array(['1-25', '500-1000', '26-100', '101-500', 'More than 1000'],
      dtype=object)

In [23]:
object_df['company_size'].value_counts()

company_size
1-25              3717
26-100            2365
101-500           1433
500-1000           727
More than 1000     128
Name: count, dtype: int64

In [31]:
df

,catcher_id,jobma_catcher_title,jobma_catcher_otype,jobma_catcher_status,jobma_catcher_type,is_premium,jobma_verified,subscription_status,sub_user,per_sub_user,...,credit_given,currency_val,times_of_subscription,kits_count,position_created,number_of_invitations,pitchers_counts,def_interview_counts,interview_counts,ai_interview_counts
0,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
1,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
2,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
3,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
4,106,0,1,-1,0,1,1,2,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7923,9319,4,1,1,1,0,1,1,999,100,...,0,1.0,1,1.0,400.0,1.0,1.0,1.0,0.0,0.0
7924,9365,0,1,1,1,1,1,1,21,100,...,50,1.0,1,0.0,4.0,25.0,5.0,7.0,0.0,0.0
7925,9405,1,1,1,1,0,1,1,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7926,9413,0,1,1,1,0,1,1,10,100,...,150,1.0,1,1.0,2.0,3.0,0.0,0.0,0.0,0.0
7927,9445,1,1,1,1,0,1,1,10,100,...,150,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df.duplicated().sum()

np.int64(442)

In [26]:
df.drop_duplicates(inplace=True)

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df

,catcher_id,jobma_catcher_title,jobma_catcher_otype,jobma_catcher_status,jobma_catcher_type,is_premium,jobma_verified,subscription_status,sub_user,per_sub_user,...,credit_given,currency_val,times_of_subscription,kits_count,position_created,number_of_invitations,pitchers_counts,def_interview_counts,interview_counts,ai_interview_counts
0,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
2,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
4,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
6,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
8,106,0,1,-1,0,1,1,2,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8365,9319,4,1,1,1,0,1,1,999,100,...,0,1.0,1,1.0,400.0,1.0,1.0,1.0,0.0,0.0
8366,9365,0,1,1,1,1,1,1,21,100,...,50,1.0,1,0.0,4.0,25.0,5.0,7.0,0.0,0.0
8367,9405,1,1,1,1,0,1,1,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8368,9413,0,1,1,1,0,1,1,10,100,...,150,1.0,1,1.0,2.0,3.0,0.0,0.0,0.0,0.0
8369,9445,1,1,1,1,0,1,1,10,100,...,150,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
df =df.reset_index(drop=True)

In [30]:
df

,catcher_id,jobma_catcher_title,jobma_catcher_otype,jobma_catcher_status,jobma_catcher_type,is_premium,jobma_verified,subscription_status,sub_user,per_sub_user,...,credit_given,currency_val,times_of_subscription,kits_count,position_created,number_of_invitations,pitchers_counts,def_interview_counts,interview_counts,ai_interview_counts
0,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
1,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
2,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
3,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
4,106,0,1,-1,0,1,1,2,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7923,9319,4,1,1,1,0,1,1,999,100,...,0,1.0,1,1.0,400.0,1.0,1.0,1.0,0.0,0.0
7924,9365,0,1,1,1,1,1,1,21,100,...,50,1.0,1,0.0,4.0,25.0,5.0,7.0,0.0,0.0
7925,9405,1,1,1,1,0,1,1,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7926,9413,0,1,1,1,0,1,1,10,100,...,150,1.0,1,1.0,2.0,3.0,0.0,0.0,0.0,0.0
7927,9445,1,1,1,1,0,1,1,10,100,...,150,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
duplicates = df[df.duplicated(subset=['catcher_id'], keep=False)]
duplicates

,catcher_id,jobma_catcher_title,jobma_catcher_otype,jobma_catcher_status,jobma_catcher_type,is_premium,jobma_verified,subscription_status,sub_user,per_sub_user,...,credit_given,currency_val,times_of_subscription,kits_count,position_created,number_of_invitations,pitchers_counts,def_interview_counts,interview_counts,ai_interview_counts
0,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
1,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
2,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
3,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
21,151,0,1,-1,0,1,1,2,999,100,...,0,1.0,2,1.0,1.0,0.0,4.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7912,9283,1,1,1,1,0,1,2,10,100,...,150,1.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7917,9299,1,1,1,1,0,1,1,1,100,...,0,1.0,2,1.0,4.0,2.0,2.0,0.0,0.0,2.0
7918,9299,1,1,1,1,0,1,1,1,100,...,0,1.0,2,1.0,4.0,2.0,2.0,0.0,0.0,2.0
7921,9315,1,1,1,1,0,1,1,999,100,...,0,1.0,1,10.0,18.0,152.0,41.0,51.0,6.0,0.0
7922,9315,1,1,1,1,0,1,1,999,100,...,0,1.0,1,10.0,18.0,152.0,41.0,51.0,6.0,0.0

In [35]:
df =df.drop_duplicates(subset=['catcher_id'], keep='first').reset_index(drop=True)

In [36]:
df

,catcher_id,jobma_catcher_title,jobma_catcher_otype,jobma_catcher_status,jobma_catcher_type,is_premium,jobma_verified,subscription_status,sub_user,per_sub_user,...,credit_given,currency_val,times_of_subscription,kits_count,position_created,number_of_invitations,pitchers_counts,def_interview_counts,interview_counts,ai_interview_counts
0,92,0,1,1,1,1,1,2,999,100,...,0,1.0,2,2.0,825.0,7.0,17640.0,3.0,2.0,0.0
1,106,0,1,-1,0,1,1,2,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,124,0,1,1,0,1,1,2,999,100,...,0,1.0,1,0.0,1.0,0.0,3.0,0.0,0.0,0.0
3,125,0,1,1,0,1,1,2,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,126,0,1,1,0,1,1,2,999,100,...,0,1.0,1,0.0,1.0,0.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5524,9319,4,1,1,1,0,1,1,999,100,...,0,1.0,1,1.0,400.0,1.0,1.0,1.0,0.0,0.0
5525,9365,0,1,1,1,1,1,1,21,100,...,50,1.0,1,0.0,4.0,25.0,5.0,7.0,0.0,0.0
5526,9405,1,1,1,1,0,1,1,999,100,...,0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5527,9413,0,1,1,1,0,1,1,10,100,...,150,1.0,1,1.0,2.0,3.0,0.0,0.0,0.0,0.0
5528,9445,1,1,1,1,0,1,1,10,100,...,150,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,5519,5520,5521,5522,5523,5524,5525,5526,5527,5528
catcher_id,92,106,124,125,126,127,128,129,130,131,...,9297,9299,9311,9313,9315,9319,9365,9405,9413,9445
jobma_catcher_title,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,1,4,0,1,0,1
jobma_catcher_otype,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
jobma_catcher_status,1,-1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
jobma_catcher_type,1,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
is_premium,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,0
jobma_verified,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
subscription_status,2,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
sub_user,999,999,999,999,999,999,999,999,999,999,...,999,1,10,1,999,999,21,999,10,10
per_sub_user,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
live_interview_credit,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0
pre_recorded_credit,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,9.0,1.0,1.0,3.0,1.0,1.0,1.0
ai_live_interview_credit,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
interview_cost_type,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,1,0,1,0,0
referral_credit,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
company_size,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,1-25,...,500-1000,1-25,1-25,500-1000,More than 1000,1-25,26-100,1-25,101-500,1-25
ai_live_interview,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,1,0
days_since_creation,3066.0,4511.0,4169.0,4166.0,4162.0,4156.0,4153.0,4151.0,4145.0,4117.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
confirmed,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
number_of_logins,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,2,1,1,1,1,3
credit_amount,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wallet_amount,34.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,500000.0,0.0,150.0,0.0,500000.0,500000.0,137.0,500000.0,15000.0,150.0
plan_type,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
is_unlimited,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
trial_account_type,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
billing_cycle_status,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
subscription_amount,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10000.0,10000.0,150.0,50.0,10000.0,0.0,50.0,0.0,150.0,0.0
credit_given,0,0,0,0,0,0,0,0,0,0,...,0,0,150,50,0,0,50,0,150,150
currency_val,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
times_of_subscription,2,1,1,1,1,1,1,1,1,1,...,1,2,1,1,1,1,1,1,1,1
kits_count,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,10.0,1.0,0.0,0.0,1.0,0.0
position_created,825.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,4.0,0.0,0.0,18.0,400.0,4.0,0.0,2.0,0.0
number_of_invitations,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,1.0,152.0,1.0,25.0,0.0,3.0,0.0
pitchers_counts,17640.0,0.0,3.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,...,0.0,2.0,0.0,0.0,41.0,1.0,5.0,0.0,0.0,0.0
def_interview_counts,3.0,0.0,0.0,0.0,0.0,28.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,51.0,1.0,7.0,0.0,0.0,0.0
interview_counts,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0
ai_interview_counts,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0