In [1]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [2]:
#candidate interview response data
jobma_ai_interviews_df = pd.read_sql("SELECT * FROM jobma_ai_interviews", engine)

In [3]:
jobma_ai_interviews_df.shape

(74, 17)

In [4]:
jobma_ai_interviews_df.T

,0,1,2,3,4,5,6,7,8,9,...,64,65,66,67,68,69,70,71,72,73
id,1,3,5,7,9,11,13,15,17,19,...,131,133,135,137,139,141,143,145,147,149
jobma_post_id,33421,33421,33421,33421,33421,33421,33421,33421,33421,33421,...,34139,33421,33421,33421,33421,33421,33421,33421,35821,35821
jobma_pitcher_id,1124457,1124467,1124467,1124491,1124491,1124491,1124525,1124529,1124529,1124579,...,1125885,1125891,1125887,1125929,1125955,1125957,1125963,1126385,1126849,1126849
jobma_catcher_id,1873,1873,1873,1873,1873,1873,1873,1873,1873,1873,...,9299,1873,1873,1873,1873,1873,1873,1873,1873,1873
interview_applied_id,64807,64811,64811,64827,64827,64827,64837,64839,64839,64841,...,65355,65365,65359,65383,65395,65397,65401,65515,65665,65667
jobma_invitation_id,574457,574473,574501,574505,574521,574525,574557,574561,574563,574611,...,576259,576267,576275,576319,576349,576351,576357,576827,577327,577331
jobma_answers,"{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""video_file"": """", ""evaluated_ans"":...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...",...,"{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""video_file"": """", ""evaluated_ans"":...","{""answer"": {""feedback"": {""d"": {""score"": 0, ""re...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""feedback"": {""overall"": {""score"": ...","{""answer"": {""video_file"": """", ""evaluated_ans"":...","{""answer"": {""video_file"": """", ""evaluated_ans"":...","{""answer"": {""video_file"": """", ""evaluated_ans"":..."
payment_status,1,1,1,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
interview_rate,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0
interview_credit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0
view_date,NaT,2025-02-04 11:07:02,2025-02-04 11:07:02,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,2025-03-06 10:29:01,2025-03-10 05:57:08,2025-03-06 10:27:28,2025-03-06 10:27:22,2025-03-06 10:27:15,2025-02-12 08:13:49,2025-03-20 07:37:42,NaT,2025-04-03 09:23:41
subscription_type,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
interview_cost_type,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cron_status,2,1,1,1,1,1,2,1,1,2,...,1,2,1,2,2,2,2,0,0,0
deleted_at,NaT,NaT,NaT,NaT,NaT,2024-12-17 05:13:06,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
created_at,2024-11-25 10:24:56,2024-11-25 11:20:05,2024-11-26 06:49:15,2024-11-26 06:55:20,2024-11-26 10:52:02,2024-11-26 11:02:34,2024-11-27 05:00:35,2024-11-27 05:19:32,2024-11-27 12:50:26,2024-11-28 12:58:11,...,2025-01-23 06:21:23,2025-01-23 07:17:38,2025-01-23 08:08:24,2025-01-24 06:36:21,2025-01-27 06:19:36,2025-01-27 06:36:02,2025-01-27 07:30:56,2025-02-13 07:23:46,2025-03-11 11:32:37,2025-03-11 11:55:22
updated_at,2025-01-22 12:42:49,2025-02-04 11:07:02,2025-02-04 11:07:02,2025-01-22 12:42:49,2025-01-22 12:42:49,2025-01-22 12:42:49,2025-01-22 12:42:49,2025-01-22 12:42:49,2025-01-22 12:42:49,2025-01-22 12:42:49,...,2025-01-23 12:01:03,2025-03-06 10:29:01,2025-03-10 05:57:08,2025-03-06 10:27:28,2025-03-06 10:27:22,2025-03-06 10:27:15,2025-02-12 08:13:49,2025-03-20 07:37:42,2025-03-11 11:32:37,2025-04-03 09:23:41

In [5]:
# ai_interviews_df=jobma_ai_interviews_df[['id',
#                                         # 'jobma_post_id',#@8 
#                                         # 'jobma_pitcher_id', #@66 #33421--49, 34089--13, 
#                                         'jobma_catcher_id',#@3,  64827-3, 64811-2....

#                                         # 'interview_applied_id',#@68, 64827--3, 648112 
#                                         'jobma_invitation_id',#@73 575621-2, 574473--1
#                                         # 'jobma_answers', #@72 Video answers, evaluations dictionary

#                                         # 'payment_status', #@2 1,0
#                                         'interview_rate',#@3,  1.0, 0.0, 2.0...............>>??
#                                         'interview_credit',#@2   1.0, Nan, 2.0
#                                         # 'view_date',#date when does it view or evaluated

#                                         'subscription_type',#@1  0 in all
#                                         'interview_cost_type',#@1  0 in all
#                                         'cron_status',#@3   1,2,0-->1,2
#                                         # 'deleted_at',

#                                         # 'created_at',
#                                         # 'updated_at'
#                                        ]]

In [9]:
ai_interviews_df = jobma_ai_interviews_df[['id',
                                           'jobma_catcher_id',#@3,  64827-3, 64811-2....
                                           'interview_rate',#@3,  1.0, 0.0, 2.0...............>>??
                                           'interview_credit',#@2   1.0, Nan, 2.0
                                          ]]

In [10]:
jobma_ai_interviews_df.shape, ai_interviews_df.shape

((74, 17), (74, 4))

In [11]:
ai_interviews_df

     id  jobma_catcher_id  interview_rate  interview_credit
0     1              1873             0.0               NaN
1     3              1873             0.0               NaN
2     5              1873             0.0               NaN
3     7              1873             0.0               NaN
4     9              1873             0.0               NaN
..  ...               ...             ...               ...
69  141              1873             1.0               1.0
70  143              1873             1.0               1.0
71  145              1873             2.0               2.0
72  147              1873             2.0               2.0
73  149              1873             2.0               2.0

[74 rows x 4 columns]

In [12]:
ai_interviews_df.nunique()

id                  74
jobma_catcher_id     3
interview_rate       3
interview_credit     2
dtype: int64

In [13]:
ai_interviews_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

C:\Users\SSI\AppData\Local\Temp\ipykernel_9556\1785853826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ai_interviews_df.rename(columns={'jobma_catcher_id': 'catcher_id'}, inplace=True)

In [14]:
ai_interviews_df['ai_interview_counts'] = ai_interviews_df['catcher_id'].map(ai_interviews_df['catcher_id'].value_counts())

C:\Users\SSI\AppData\Local\Temp\ipykernel_9556\2551229909.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ai_interviews_df['ai_interview_counts'] = ai_interviews_df['catcher_id'].map(ai_interviews_df['catcher_id'].value_counts())

In [15]:
ai_interviews_df

     id  catcher_id  interview_rate  interview_credit  ai_interview_counts
0     1        1873             0.0               NaN                   67
1     3        1873             0.0               NaN                   67
2     5        1873             0.0               NaN                   67
3     7        1873             0.0               NaN                   67
4     9        1873             0.0               NaN                   67
..  ...         ...             ...               ...                  ...
69  141        1873             1.0               1.0                   67
70  143        1873             1.0               1.0                   67
71  145        1873             2.0               2.0                   67
72  147        1873             2.0               2.0                   67
73  149        1873             2.0               2.0                   67

[74 rows x 5 columns]

In [18]:
ai_interviews_df=ai_interviews_df[['catcher_id', 'ai_interview_counts']]

In [19]:
ai_interviews_df.shape

(74, 2)

In [20]:
ai_interviews_df.duplicated().sum()

np.int64(71)

In [21]:
ai_interviews_df.drop_duplicates(inplace=True)

C:\Users\SSI\AppData\Local\Temp\ipykernel_9556\2413312109.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ai_interviews_df.drop_duplicates(inplace=True)

In [22]:
ai_interviews_df

    catcher_id  ai_interview_counts
0         1873                   67
15        8597                    5
63        9299                    2

In [23]:
ai_interviews_df.to_csv("ai_interviews_df.csv", index=False)