In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

In [2]:
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")
df = pd.read_sql("SELECT * FROM subscription_history", engine)

In [3]:
df.shape

(11049, 34)

In [4]:
df=df[['catcher_id',
       'premium_plan',
       'subscription_amount',  # diffrenet may be taken bu client--plan prices ----->May be................??
       'credit_given',  #@37,   0,50,600,.................................How much credits they got on buying
       'currency',  # 0,1-------------------------------------------------------------meaning of 0 ,1--------??
       'currency_val',
      ]]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11049 entries, 0 to 11048
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   catcher_id           11049 non-null  int64
 1   premium_plan         10929 non-null  object
 2   subscription_amount  11049 non-null  float64
 3   credit_given         11049 non-null  int64
 4   currency             11049 non-null  object
 5   currency_val         11049 non-null  float64
dtypes: float64(2), int64(2), object(2)
memory usage: 518.0+ KB

In [6]:
df.nunique()

catcher_id             5560
premium_plan            801
subscription_amount     344
credit_given             37
currency                  2
currency_val             39
dtype: int64

In [18]:
df['currency'].value_counts()

currency
0    3129
1    2431
Name: count, dtype: int64

In [8]:
# # Sum of subscription_amount
# df['subscription_sum'] = df.groupby('catcher_id')['subscription_amount'].transform('sum')

# # Count of subscription_amount
# df['subscription_count'] = df.groupby('catcher_id')['subscription_amount'].transform('count')

In [9]:
df = df.groupby('catcher_id').agg(subscription_sum=('subscription_amount', 'sum'),
                                  subscription_count=('subscription_amount', 'count'),
                                  currency=('currency', 'first')
                                 ).reset_index()

In [10]:
df.isna().sum()

catcher_id            0
subscription_sum      0
subscription_count    0
currency              0
dtype: int64

In [11]:
df.nunique()

catcher_id            5560
subscription_sum       856
subscription_count      37
currency                 2
dtype: int64

In [12]:
df

      catcher_id  subscription_sum  subscription_count currency
0             92             199.0                   2        0
1            106               0.0                   1        0
2            124               0.0                   1        0
3            125               0.0                   1        0
4            126               0.0                   1        0
...          ...               ...                 ...      ...
5555        9319               0.0                   1        1
5556        9365              50.0                   1        0
5557        9405               0.0                   1        1
5558        9413             150.0                   1        0
5559        9445               0.0                   1        0

[5560 rows x 4 columns]

In [13]:
df.nunique()

catcher_id            5560
subscription_sum       856
subscription_count      37
currency                 2
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df

      catcher_id  subscription_sum  subscription_count currency
0             92             199.0                   2        0
1            106               0.0                   1        0
2            124               0.0                   1        0
3            125               0.0                   1        0
4            126               0.0                   1        0
...          ...               ...                 ...      ...
5555        9319               0.0                   1        1
5556        9365              50.0                   1        0
5557        9405               0.0                   1        1
5558        9413             150.0                   1        0
5559        9445               0.0                   1        0

[5560 rows x 4 columns]

In [17]:
df.loc[df['catcher_id'] == 1873]

     catcher_id  subscription_sum  subscription_count currency
849        1873         1243365.0                 238        0

In [20]:
df.isna().sum()

catcher_id            0
subscription_sum      0
subscription_count    0
currency              0
dtype: int64

In [19]:
df.to_csv("final_subscrption_df.csv", index=False)