In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

In [2]:
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")
df = pd.read_sql("SELECT * FROM subscription_history", engine)

In [3]:
df

,id,catcher_id,catcher_username,catcher_email,sub_user_id,subscription_id,premium_plan_id,premium_plan,transaction_id,subscription_amount,...,e_invoice,cheque_number,banker,cheque_amount,cheque_image,cancel_date,invoice_suffix,radioGstValue,created_at,updated_at
0,2,899,,,NaN,1,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",2V065953EF212362V,0.0,...,0,None,None,0.0,None,None,0,1,2017-11-03 05:18:44,2023-11-22 12:43:34
1,3,900,,,NaN,1,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",9BY60034LB809061M,0.0,...,0,None,None,0.0,None,None,0,1,2017-11-03 07:47:12,2023-12-15 12:59:57
2,4,900,,,NaN,1,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",3KH319283K655734K,0.0,...,0,None,None,0.0,None,None,0,1,2017-11-03 07:52:28,2021-06-11 12:41:24
3,5,900,,,NaN,1,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",3KH319283K655734K,0.0,...,0,None,None,0.0,None,None,0,1,2017-11-03 07:52:45,2021-06-11 12:41:24
4,6,900,,,NaN,1,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",3KH319283K655734K,0.0,...,0,None,None,0.0,None,None,0,1,2017-11-03 07:53:15,2021-06-11 12:41:24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11044,11589,7099,Admin,None,NaN,1,7.0,"{""subscription_charges"":""10000"",""email_support...",70991734584191,10000.0,...,1,,,0.0,None,None,3891,1,2024-12-19 04:56:31,2025-01-27 09:20:23
11045,11591,9299,Admin,None,NaN,1,2.0,"{""subscription_charges"":""50"",""email_support"":""...",92991737610906,50.0,...,1,,,0.0,None,None,0,1,2025-01-23 05:41:46,2025-01-23 05:41:46
11046,11593,7099,Admin,None,NaN,1,6.0,"{""subscription_charges"":""25000"",""email_support...",70991737969623,25000.0,...,1,,,0.0,None,None,3892,1,2025-01-27 09:20:23,2025-01-27 09:20:23
11047,11595,8565,Admin,None,NaN,1,3.0,"{""subscription_charges"":""150"",""email_support"":...",85651741263288,5000.0,...,1,,,0.0,None,None,0,1,2025-03-06 12:14:48,2025-03-18 12:04:36
11048,11597,9445,Serge brian,None,NaN,1,3.0,"{""subscription_charges"":""150"",""email_support"":...",79253611633,0.0,...,0,None,None,0.0,None,None,0,1,2025-03-28 05:15:12,2025-03-28 05:15:12

In [4]:
df=df[['catcher_id',
       'premium_plan',
       'subscription_amount',  # diffrenet may be taken bu client--plan prices ----->May be................??
       'credit_given',  #@37,   0,50,600,.................................How much credits they got on buying
       'currency',  # 0,1-------------------------------------------------------------meaning of 0 ,1--------??
       'currency_val',
      ]]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11049 entries, 0 to 11048
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   catcher_id           11049 non-null  int64
 1   premium_plan         10929 non-null  object
 2   subscription_amount  11049 non-null  float64
 3   credit_given         11049 non-null  int64
 4   currency             11049 non-null  object
 5   currency_val         11049 non-null  float64
dtypes: float64(2), int64(2), object(2)
memory usage: 518.0+ KB

In [6]:
df.nunique()

catcher_id             5560
premium_plan            801
subscription_amount     344
credit_given             37
currency                  2
currency_val             39
dtype: int64

In [7]:
df['currency'].value_counts()

currency
0    6376
1    4673
Name: count, dtype: int64

In [8]:
# # Sum of subscription_amount
# df['subscription_sum'] = df.groupby('catcher_id')['subscription_amount'].transform('sum')

# # Count of subscription_amount
# df['subscription_count'] = df.groupby('catcher_id')['subscription_amount'].transform('count')

In [9]:
df = df.groupby('catcher_id').agg(subscription_sum=('subscription_amount', 'sum'),
                                  subscription_count=('subscription_amount', 'count'),
                                  currency=('currency', 'first')
                                 ).reset_index()

In [10]:
df.isna().sum()

catcher_id            0
subscription_sum      0
subscription_count    0
currency              0
dtype: int64

In [11]:
df.nunique()

catcher_id            5560
subscription_sum       856
subscription_count      37
currency                 2
dtype: int64

In [12]:
df

      catcher_id  subscription_sum  subscription_count currency
0             92             199.0                   2        0
1            106               0.0                   1        0
2            124               0.0                   1        0
3            125               0.0                   1        0
4            126               0.0                   1        0
...          ...               ...                 ...      ...
5555        9319               0.0                   1        1
5556        9365              50.0                   1        0
5557        9405               0.0                   1        1
5558        9413             150.0                   1        0
5559        9445               0.0                   1        0

[5560 rows x 4 columns]

In [13]:
df.nunique()

catcher_id            5560
subscription_sum       856
subscription_count      37
currency                 2
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df

      catcher_id  subscription_sum  subscription_count currency
0             92             199.0                   2        0
1            106               0.0                   1        0
2            124               0.0                   1        0
3            125               0.0                   1        0
4            126               0.0                   1        0
...          ...               ...                 ...      ...
5555        9319               0.0                   1        1
5556        9365              50.0                   1        0
5557        9405               0.0                   1        1
5558        9413             150.0                   1        0
5559        9445               0.0                   1        0

[5560 rows x 4 columns]

In [16]:
df.loc[df['catcher_id'] == 1873]

     catcher_id  subscription_sum  subscription_count currency
849        1873         1243365.0                 238        0

In [17]:
df.isna().sum()

catcher_id            0
subscription_sum      0
subscription_count    0
currency              0
dtype: int64

In [ ]:
sns.histplot(data=df)