In [ ]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/test")

def clean_catcher_data(engine):
    catcher = pd.read_sql("SELECT jobma_catcher_id, is_premium, subscription_status, company_size, jobma_catcher_parent FROM jobma_catcher WHERE jobma_verified IN (1, '1')", engine).copy()
    catcher.replace("", np.nan, inplace=True)
    catcher['is_premium'] = pd.to_numeric(catcher['is_premium'], errors='coerce').fillna(0).astype(int)
    catcher['subscription_status'] = pd.to_numeric(catcher['subscription_status'], errors='coerce').replace(0, 2).fillna(2).astype(int)
    sub_accounts = catcher['jobma_catcher_parent'].value_counts()
    catcher['sub_user'] = catcher['jobma_catcher_id'].map(sub_accounts).fillna(0).astype(int)
    return catcher
catcher_df = clean_catcher_data(engine)

def clean_wallet_data(engine):
    wallet = pd.read_sql("SELECT catcher_id AS jobma_catcher_id, wallet_amount, is_unlimited FROM wallet", engine).copy()
    wallet['wallet_amount'] = pd.to_numeric(wallet['wallet_amount'], errors='coerce').fillna(0)
    wallet['is_unlimited'] = pd.to_numeric(wallet['is_unlimited'], errors='coerce').fillna(0).astype(int)
    return wallet
wallet_df = clean_wallet_data(engine)

def clean_subscription_data(engine):
    subscription = pd.read_sql("SELECT catcher_id AS jobma_catcher_id, subscription_amount, currency FROM subscription_history", engine).copy()
    subscription['subscription_amount'] = subscription['subscription_amount'].where(subscription['subscription_amount'] > 0, 0)
    subscription['subscription_amount'] = pd.to_numeric(subscription['subscription_amount'], errors='coerce').fillna(0)
    subscription['subscription_amount'] = np.where(subscription['currency'] == 0, subscription['subscription_amount'].round(1),
                                                   (subscription['subscription_amount'] / 85).round(1))
    subscription_agg = subscription.groupby('jobma_catcher_id').agg(subscription_sum=('subscription_amount', 'sum'),
                                                                    subscription_count=('jobma_catcher_id', 'count')).reset_index()
    subscription_agg['subscription_count'] = subscription_agg['subscription_count'].astype(int)
    return subscription_agg
subscription_df = clean_subscription_data(engine)


def clean_login_data(engine):
    login = pd.read_sql("SELECT jobma_user_id AS jobma_catcher_id, jobma_last_login FROM jobma_login", engine).copy()
    login['jobma_last_login'] = pd.to_datetime(login['jobma_last_login'], errors='coerce')
    login['since_last_login'] = (pd.Timestamp('today') - login['jobma_last_login']).dt.days
    login['since_last_login'] = login['since_last_login'].fillna(-1)  # Sentinel for 'No login'
    
    login_grouped = login.groupby('jobma_catcher_id').agg(since_last_login=('since_last_login', 'min')).reset_index()

    # Categorize login recency
    bins = [-1, 0, 30, 90, 180, 365, float('inf')]
    labels = ['No login', 'Less than 1 month', '1-3 months', '3-6 months', '6-12 months', 'More than 1 year']
    login_grouped['since_last_login'] = pd.cut(login_grouped['since_last_login'], bins=bins, labels=labels, right=False)
    
    return login_grouped
login_df = clean_login_data(engine)

In [4]:
dfs_to_merge = [wallet_df, subscription_df, login_df]
for i in dfs_to_merge:
    catcher_df = pd.merge(catcher_df, i, how='left', on='jobma_catcher_id')

In [5]:
catcher_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6116 entries, 0 to 6115
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   jobma_catcher_id      6116 non-null   int64
 1   is_premium            6116 non-null   int64
 2   subscription_status   6116 non-null   int64
 3   company_size          5630 non-null   object
 4   jobma_catcher_parent  6116 non-null   int64
 5   sub_user              6116 non-null   int64
 6   wallet_amount         4461 non-null   float64
 7   is_unlimited          4461 non-null   float64
 8   subscription_sum      4462 non-null   float64
 9   subscription_count    4462 non-null   float64
 10  since_last_login      6114 non-null   category
dtypes: category(1), float64(4), int64(5), object(1)
memory usage: 484.1+ KB

In [6]:
#invitations

In [7]:
def clean_invitations_data(engine):
    invitations= pd.read_sql("SELECT jobma_catcher_id, FROM jobma_pitcher_invitations", con= engine)
    invitations= invitations.groupby('jobma_catcher_id').size().reset_index(name='invitations')
    return invitations

def clean_pre_recorded_kit_data(engine):
    pre_recorded_kit = pd.read_sql("SELECT catcher_id as jobma_catcher_id  FROM job_assessment_kit", engine)
    pre_recorded_kit = pre_recorded_kit.groupby('jobma_catcher_id').size().reset_index(name='pre_recorded_kit_counts')
    return pre_recorded_kit

def clean_job_posting_data(engine):
    job_posted = pd.read_sql("SELECT jobma_catcher_id FROM jobma_employer_job_posting", engine).copy()
    job_posted = job_posted.groupby('jobma_catcher_id').size().reset_index(name='jobs_posted')
    return job_posted

def clean_pre_rec_interviews_data(engine):
    pre_rec_interviews = pd.read_sql("SELECT jobma_catcher_id FROM jobma_interviews", con = engine).copy()
    pre_rec_interviews = pre_rec_interviews.groupby('jobma_catcher_id').size().reset_index(name='pre_rec_interview_taken')
    return pre_rec_interviews

In [8]:
# Load all individual cleaned data and Merging

In [9]:
invitations_df = clean_invitations_data(engine)
pre_recorded_kit_df = clean_pre_recorded_kit_data(engine)
job_posted_df = clean_job_posting_data(engine)
pre_rec_interviews_df = clean_pre_rec_interviews_data(engine)
final_df = catcher_df.copy()
dfs_to_merge = [invitations_df, pre_recorded_kit_df, job_posted_df, pre_rec_interviews_df]
for df in dfs_to_merge:
    final_df = pd.merge(final_df, df, how='left', on='jobma_catcher_id')

In [10]:
print("catcher_df:", catcher_df.shape)
print("wallet_df:", wallet_df.shape)
print("subscription_df:", subscription_df.shape)
print("invitations_df:", invitations_df.shape)
print("pre_recorded_kit_df:", pre_recorded_kit_df.shape)
print("job_posted_df:", job_posted_df.shape)
print("pre_rec_interviews_df:", pre_rec_interviews_df.shape)
print("login_df:", login_df.shape)
print("final_df:", final_df.shape)

catcher_df: (6116, 11)
wallet_df: (4479, 3)
subscription_df: (4477, 3)
invitations_df: (1171, 2)
pre_recorded_kit_df: (1192, 2)
job_posted_df: (1127, 2)
pre_rec_interviews_df: (857, 2)
login_df: (9711, 2)
final_df: (6116, 15)

In [11]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6116 entries, 0 to 6115
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   jobma_catcher_id         6116 non-null   int64
 1   is_premium               6116 non-null   int64
 2   subscription_status      6116 non-null   int64
 3   company_size             5630 non-null   object
 4   jobma_catcher_parent     6116 non-null   int64
 5   sub_user                 6116 non-null   int64
 6   wallet_amount            4461 non-null   float64
 7   is_unlimited             4461 non-null   float64
 8   subscription_sum         4462 non-null   float64
 9   subscription_count       4462 non-null   float64
 10  since_last_login         6114 non-null   category
 11  invitations              1144 non-null   float64
 12  pre_recorded_kit_counts  1180 non-null   float64
 13  jobs_posted              1124 non-null   float64
 14  pre_rec_interview_taken  846 non-null    float64
dtypes: category(1), float64(8), int64(5), object(1)
memory usage: 675.2+ KB

In [12]:
final_df.tail(20)

,jobma_catcher_id,is_premium,subscription_status,company_size,jobma_catcher_parent,sub_user,wallet_amount,is_unlimited,subscription_sum,subscription_count,since_last_login,invitations,pre_recorded_kit_counts,jobs_posted,pre_rec_interview_taken
6096,10517,0,1,1-25,0,0,50.0,0.0,0.0,1.0,No login,NaN,NaN,NaN,NaN
6097,10518,0,1,1-25,0,0,150.0,0.0,0.0,1.0,6-12 months,NaN,NaN,1.0,NaN
6098,10519,0,1,101-500,0,0,150.0,0.0,3.0,2.0,No login,NaN,1.0,1.0,NaN
6099,10520,0,1,26-100,10121,0,NaN,NaN,NaN,NaN,No login,NaN,NaN,NaN,NaN
6100,10521,0,1,1-25,0,1,500000.0,1.0,117.6,2.0,6-12 months,24.0,1.0,16.0,7.0
6101,10522,0,1,1-25,0,0,50.0,0.0,0.0,1.0,6-12 months,12.0,1.0,1.0,NaN
6102,10523,0,1,1-25,0,1,47.0,0.0,647.1,3.0,6-12 months,2.0,1.0,1.0,NaN
6103,10524,0,1,26-100,0,0,149.0,0.0,294.1,1.0,6-12 months,1.0,1.0,1.0,1.0
6104,10525,0,1,26-100,0,0,500000.0,1.0,117.6,1.0,6-12 months,1.0,1.0,1.0,NaN
6105,10526,0,1,101-500,0,0,500000.0,1.0,117.6,1.0,No login,9.0,4.0,3.0,2.0
6106,10527,0,1,101-500,10489,0,NaN,NaN,NaN,NaN,No login,10.0,1.0,NaN,9.0
6107,10528,0,1,26-100,0,0,50.0,0.0,1.2,1.0,No login,1.0,1.0,1.0,NaN
6108,10529,0,1,1-25,0,0,35.0,0.0,1.2,1.0,6-12 months,3.0,1.0,2.0,3.0
6109,10530,0,1,1-25,0,0,147.0,0.0,0.0,1.0,No login,3.0,3.0,5.0,1.0
6110,10531,0,1,26-100,0,0,50.0,0.0,1.2,1.0,6-12 months,NaN,NaN,NaN,NaN
6111,10532,0,1,1-25,10523,0,NaN,NaN,NaN,NaN,No login,2.0,NaN,NaN,NaN
6112,10533,0,1,1-25,0,0,49.0,0.0,0.0,1.0,No login,2.0,2.0,2.0,1.0
6113,10534,0,1,1-25,10521,0,NaN,NaN,NaN,NaN,No login,5.0,NaN,8.0,5.0
6114,10535,0,1,1-25,9579,0,NaN,NaN,NaN,NaN,No login,NaN,NaN,NaN,NaN
6115,10536,0,1,1-25,0,0,48.0,0.0,0.0,1.0,6-12 months,2.0,1.0,1.0,2.0

In [13]:
final_df.nunique()

jobma_catcher_id           6116
is_premium                    2
subscription_status           2
company_size                  5
jobma_catcher_parent       1010
sub_user                     19
wallet_amount               179
is_unlimited                  2
subscription_sum            733
subscription_count           34
since_last_login              3
invitations                 131
pre_recorded_kit_counts      56
jobs_posted                  50
pre_rec_interview_taken      91
dtype: int64

In [14]:
final_df['since_last_login'].value_counts()

since_last_login
More than 1 year     4526
No login             1515
6-12 months            73
Less than 1 month       0
3-6 months              0
1-3 months              0
Name: count, dtype: int64

In [15]:
final_df.isna().sum()

jobma_catcher_id              0
is_premium                    0
subscription_status           0
company_size                486
jobma_catcher_parent          0
sub_user                      0
wallet_amount              1655
is_unlimited               1655
subscription_sum           1654
subscription_count         1654
since_last_login              2
invitations                4972
pre_recorded_kit_counts    4936
jobs_posted                4992
pre_rec_interview_taken    5270
dtype: int64

In [16]:
final_df[final_df.select_dtypes(include='float64').columns] = final_df.select_dtypes(include='float64').fillna(0)

In [17]:
final_df

,jobma_catcher_id,is_premium,subscription_status,company_size,jobma_catcher_parent,sub_user,wallet_amount,is_unlimited,subscription_sum,subscription_count,since_last_login,invitations,pre_recorded_kit_counts,jobs_posted,pre_rec_interview_taken
0,2656,0,1,1-25,0,1,66666.0,1.0,176.5,1.0,More than 1 year,4.0,2.0,1.0,1.0
1,2935,0,2,26-100,0,0,60.0,0.0,0.6,1.0,More than 1 year,0.0,0.0,0.0,0.0
2,2937,0,2,101-500,0,0,60.0,0.0,1.4,1.0,More than 1 year,0.0,0.0,0.0,0.0
3,2938,0,1,26-100,0,0,50.0,0.0,178.8,3.0,More than 1 year,0.0,0.0,1.0,0.0
4,2939,0,2,26-100,0,0,60.0,0.0,138.8,1.0,More than 1 year,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6111,10532,0,1,1-25,10523,0,0.0,0.0,0.0,0.0,No login,2.0,0.0,0.0,0.0
6112,10533,0,1,1-25,0,0,49.0,0.0,0.0,1.0,No login,2.0,2.0,2.0,1.0
6113,10534,0,1,1-25,10521,0,0.0,0.0,0.0,0.0,No login,5.0,0.0,8.0,5.0
6114,10535,0,1,1-25,9579,0,0.0,0.0,0.0,0.0,No login,0.0,0.0,0.0,0.0
6115,10536,0,1,1-25,0,0,48.0,0.0,0.0,1.0,6-12 months,2.0,1.0,1.0,2.0

In [18]:
columns_to_sum = ['invitations', 'pre_recorded_kit_counts', 'jobs_posted', 'pre_rec_interview_taken']
final_df[columns_to_sum] = final_df[columns_to_sum].fillna(0)

# Create a mapping: parent_id -> summed child values
child_sums = final_df[final_df['jobma_catcher_parent'] != 0].groupby('jobma_catcher_parent')[columns_to_sum].sum()

# Filter only parent rows
df_parents = final_df[final_df['jobma_catcher_parent'] == 0].copy()

# Add child values to parents where jobma_catcher_id == jobma_catcher_parent
for col in columns_to_sum:
    df_parents[col] += df_parents['jobma_catcher_id'].map(child_sums[col]).fillna(0)

In [19]:
df_parents

,jobma_catcher_id,is_premium,subscription_status,company_size,jobma_catcher_parent,sub_user,wallet_amount,is_unlimited,subscription_sum,subscription_count,since_last_login,invitations,pre_recorded_kit_counts,jobs_posted,pre_rec_interview_taken
0,2656,0,1,1-25,0,1,66666.0,1.0,176.5,1.0,More than 1 year,7.0,4.0,2.0,1.0
1,2935,0,2,26-100,0,0,60.0,0.0,0.6,1.0,More than 1 year,0.0,0.0,0.0,0.0
2,2937,0,2,101-500,0,0,60.0,0.0,1.4,1.0,More than 1 year,0.0,0.0,0.0,0.0
3,2938,0,1,26-100,0,0,50.0,0.0,178.8,3.0,More than 1 year,0.0,0.0,1.0,0.0
4,2939,0,2,26-100,0,0,60.0,0.0,138.8,1.0,More than 1 year,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6108,10529,0,1,1-25,0,0,35.0,0.0,1.2,1.0,6-12 months,3.0,1.0,2.0,3.0
6109,10530,0,1,1-25,0,0,147.0,0.0,0.0,1.0,No login,3.0,3.0,5.0,1.0
6110,10531,0,1,26-100,0,0,50.0,0.0,1.2,1.0,6-12 months,0.0,0.0,0.0,0.0
6112,10533,0,1,1-25,0,0,49.0,0.0,0.0,1.0,No login,2.0,2.0,2.0,1.0
6115,10536,0,1,1-25,0,0,48.0,0.0,0.0,1.0,6-12 months,2.0,1.0,1.0,2.0

In [20]:
final_df.max(numeric_only=True)

jobma_catcher_id             10536.0
is_premium                       1.0
subscription_status              2.0
jobma_catcher_parent         10523.0
sub_user                        40.0
wallet_amount              4995968.0
is_unlimited                     1.0
subscription_sum           1398501.6
subscription_count             116.0
invitations                  50046.0
pre_recorded_kit_counts        292.0
jobs_posted                    189.0
pre_rec_interview_taken        635.0
dtype: float64

In [21]:
df_parents.max(numeric_only=True)

jobma_catcher_id             10536.0
is_premium                       1.0
subscription_status              2.0
jobma_catcher_parent             0.0
sub_user                        40.0
wallet_amount              4995968.0
is_unlimited                     1.0
subscription_sum           1398501.6
subscription_count             116.0
invitations                  50056.0
pre_recorded_kit_counts        293.0
jobs_posted                    195.0
pre_rec_interview_taken        639.0
dtype: float64

In [22]:
df_parents.min(numeric_only=True)

jobma_catcher_id           2656.0
is_premium                    0.0
subscription_status           1.0
jobma_catcher_parent          0.0
sub_user                      0.0
wallet_amount                 0.0
is_unlimited                  0.0
subscription_sum              0.0
subscription_count            0.0
invitations                   0.0
pre_recorded_kit_counts       0.0
jobs_posted                   0.0
pre_rec_interview_taken       0.0
dtype: float64

In [23]:
df_parents.nunique()

jobma_catcher_id           4466
is_premium                    2
subscription_status           2
company_size                  5
jobma_catcher_parent          1
sub_user                     19
wallet_amount               179
is_unlimited                  2
subscription_sum            733
subscription_count           35
since_last_login              3
invitations                 131
pre_recorded_kit_counts      55
jobs_posted                  55
pre_rec_interview_taken      90
dtype: int64

# Visualisation

In [24]:
qwerty

NameError: name 'qwerty' is not defined

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=final_df.copy()

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.isna().sum()

In [ ]:
pd.set_option('display.float_format', '{:.2f}'.format)
df.describe().T

In [ ]:
plt.figure(figsize=(15, 10))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt=".2f", square=True)
plt.title("Correlation Heatmap")
plt.show()

In [ ]:
plt.figure(figsize=(30,5))
sns.boxplot(data=df)

In [ ]:
sns.countplot(x=df['company_size'])

In [ ]:
plt.figure(figsize=(3,5))
sns.countplot(x=df['is_premium'])

In [ ]:
plt.figure(figsize=(3,5))
sns.countplot(x=df['subscription_status'])

In [ ]:
plt.figure(figsize=(10,5))
sns.countplot(x=df['sub_user'])

In [ ]:
plt.figure(figsize=(3,5))
sns.countplot(x=df['is_unlimited'])

In [ ]:
plt.figure(figsize=(15,5))
sns.countplot(x=df['subscription_count'])

In [ ]:
plt.figure(figsize=(30,4))
sns.countplot(x=df['jobs_posted'])

In [ ]:
plt.figure(figsize=(30,10))
sns.countplot(x=df['pre_recorded_kit_counts'])

In [ ]:
plt.figure(figsize=(50,10))
sns.countplot(x=df['pre_rec_interview_taken'])

In [ ]:
plt.figure(figsize=(100,10))
sns.countplot(x=df['invitations'])

In [ ]:
plt.figure(figsize=(100,10))
sns.countplot(x=df['wallet_amount'])

In [ ]:
plt.figure(figsize=(500, 10))
sns.countplot(x=df['subscription_sum'])

In [ ]:
df

In [ ]:
plt.figure(figsize=(8,5))
sns.countplot(x=df['since_last_login'])