In [1]:
import pandas as pd
import seaborn as sns

In [2]:
#intervies done #Interview given by candididate
interviews_df=pd.read_csv("interviews_df.csv")
interviews_online_df=pd.read_csv("interviews_online_df.csv") 
ai_interviews_df=pd.read_csv("ai_interviews_df.csv")

In [3]:
interviews_df.columns

Index(['catcher_id', 'def_interview_counts'], dtype='object')

In [4]:
interviews_online_df.columns

Index(['catcher_id', 'interview_counts'], dtype='object')

In [5]:
interviews_df.shape, interviews_online_df.shape, ai_interviews_df.shape

((865, 2), (121, 2), (3, 2))

In [6]:
interviews_def_online_df= pd.merge(interviews_df, interviews_online_df,
                                   on='catcher_id',
                                   how='outer')

In [7]:
interviews_def_online_df

     catcher_id  def_interview_counts  interview_counts
0             0                  14.0               NaN
1            51                  15.0               NaN
2            92                   3.0               2.0
3           127                  28.0               NaN
4           141                   2.0               NaN
..          ...                   ...               ...
873        9333                   NaN               1.0
874        9365                   7.0               NaN
875        9403                  10.0               NaN
876        9415                   1.0               3.0
877        9431                   1.0               NaN

[878 rows x 3 columns]

In [8]:
interviews_def_online_ai_df = pd.merge(interviews_def_online_df, ai_interviews_df,
                                       on='catcher_id',
                                       how='outer')

In [9]:
interviews_def_online_ai_df.isna().sum()

catcher_id                0
def_interview_counts     14
interview_counts        758
ai_interview_counts     876
dtype: int64

In [10]:
interviews_def_online_ai_df=interviews_def_online_ai_df.fillna(0).astype(int)

In [11]:
interviews_def_online_ai_df

     catcher_id  def_interview_counts  interview_counts  ai_interview_counts
0             0                    14                 0                    0
1            51                    15                 0                    0
2            92                     3                 2                    0
3           127                    28                 0                    0
4           141                     2                 0                    0
..          ...                   ...               ...                  ...
874        9333                     0                 1                    0
875        9365                     7                 0                    0
876        9403                    10                 0                    0
877        9415                     1                 3                    0
878        9431                     1                 0                    0

[879 rows x 4 columns]

In [12]:
interviews_def_online_ai_df.to_csv("interviews_def_online_ai_df.csv", index=False)