In [1]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/jobma")

In [2]:
# tanure, Usage
jobma_login_df = pd.read_sql("SELECT * FROM jobma_login", engine) #Usage details
jobma_wallet_df = pd.read_sql("SELECT * FROM wallet", engine) #How aggresively using + how much #account Wallet info
jobma_subscription_history_df = pd.read_sql("SELECT * FROM subscription_history", engine) #how much frequently using #subscription history

In [3]:
jobma_login_selected_df = jobma_login_df[['jobma_login_id',        #@39321 id
                                          # 'jobma_user_name',       # name
                                          # 'jobma_password',        # password
                                          # 'jobma_role_id',         #@7, 4,3,5,0,9,1,2 id----------------------------->>
                                          # 'jobma_user_id',          # id
                                          'jobma_last_login',       #@18233 almost 0000.000, None--------------------->> 
                                          'jobma_created_by',       #@4, NOne, 1, 0, 2-------------------------------->>
                                          'confirmed',              # 0,1-----1
                                          # 'confirmation_code',     #mostly null and email...
                                          'jobma_login_status',     #@4  -,0,1----------------------------------------->>
                                          # 'jobma_login_ip',        
                                          # 'forget_password',       
                                          # 'remember_token',        
                                          # 'jobma_social_login',    #2,  0,1---->0
                                          # 'password_changed_at',   
                                          'deleted_at',             #39237 is NAt value----------------------------------------------->>required all below three columns to know tenure of client
                                          'created_at',             ##---------------------------------------------------------------->> to find user tenure
                                          # 'updated_at',            ##----------------------------------------------------------------->>
                                          # 'google2fa_secret',      
                                          # 'two_factor_status',     #@0,1----->0
                                          # 'two_factor_type'        #@0,1----->0
                                         ]].copy()

In [4]:
jobma_wallet_selected_df = jobma_wallet_df[['catcher_id',   #@5560
                                            # 'id',
                                            'credit_amount',#@40,  Nan, -------------------------------------------->>??Required
                                            'wallet_amount', #amounts or balance may be ---------------------------->>??
                                            'subscription_type', #0,1    mostly------------------------->> 0
                                            'plan_type',#0,1
                                            'is_unlimited',#0, 1------------------------------------------------------>>
                                            'premium_storage',#------------------------------------------------------->>All are 0
                                            'trial_account_type',#0.0,1.0--------------------------------------------->>mostly zero   #can be used to remove and fill values
                                            # 'gst_code',#
                                            # 'billing_cycle', #not relevantdat
                                            'billing_cycle_status',#0,1 may be koi relation ho plan se ya user type se
                                            'created_at',# there may be many created and updated column--------------->> can be considered use as client age with us
                                            'updated_at'
                                         ]].copy()

In [5]:
jobma_subscription_history_selected_df = jobma_subscription_history_df[['catcher_id',  # duplicated catcher id as has buy many times
                                                                        # 'id',  # starts from 2
                                                                        # 'catcher_username', 
                                                                        # 'catcher_email', 
                                                                        'sub_user_id',  #@407 unique values,  sub users and admins too many with same id----------------->>
                                                                        'subscription_id',  # 1,2------------------------------------------------------------------------>>
                                                                        'premium_plan_id',  #@10    1.0,2.0,3.0....10.0------------------------------------>>3.0,2.0 mostly
                                                                        'premium_plan',  #@802 unique but dict------------ category of different different plans............??
                                                                        # 'transaction_id',
                                                                        'subscription_amount',  # diffrenet may be taken bu client--plan prices ----->May be................??
                                                                        'credit_given',  #@37,   0,50,600,.................................How much credits they got on buying
                                                                        # 'paypal_profile_id',
                                                                        # 'paypal_payer_id',
                                                                        'expiry_date',
                                                                        'currency',  # 0,1-------------------------------------------------------------meaning of 0 ,1--------??
                                                                        # 'premium_storage',----------------------------------------------------------all are 0...............??
                                                                        # 'igst',
                                                                        # 'cgst',
                                                                        # 'gst_code',
                                                                        'currency_val',  #@39,   1, 70 mostly 1 and 70-------------------------------------------------------->>
                                                                        # 'recurring_data',  # Categorial data #Text data
                                                                        'payment_mode',#@7, unique['1' '2' '3' '5' '' '6' '4'] , mostly 1,6,3
                                                                        'status',  #1,0 iska nahi pta hai---------------------------------------------------------------------->>
                                                                        'payment_status',#1,0-----------------------------------------------------------------------mostly 1--->>
                                                                        # 'e_invoice',
                                                                        # 'cheque_number',
                                                                        # 'banker',
                                                                        # 'cheque_amount',
                                                                        # 'cheque_image',
                                                                        # 'cancel_date',
                                                                        # 'invoice_suffix',
                                                                        # 'radioGstValue',
                                                                        # 'created_at',
                                                                        # 'updated_at'
                                                                       ]].copy()

In [6]:
jobma_login_selected_df.columns, jobma_wallet_selected_df.columns, jobma_subscription_history_selected_df.columns

(Index(['jobma_login_id', 'jobma_last_login', 'jobma_created_by', 'confirmed',
        'jobma_login_status', 'deleted_at', 'created_at'],
       dtype='object'),
 Index(['catcher_id', 'credit_amount', 'wallet_amount', 'subscription_type',
        'plan_type', 'is_unlimited', 'premium_storage', 'trial_account_type',
        'billing_cycle_status', 'created_at', 'updated_at'],
       dtype='object'),
 Index(['catcher_id', 'sub_user_id', 'subscription_id', 'premium_plan_id',
        'premium_plan', 'subscription_amount', 'credit_given', 'expiry_date',
        'currency', 'currency_val', 'payment_mode', 'status', 'payment_status'],
       dtype='object'))

In [7]:
jobma_login_selected_df.shape, jobma_wallet_selected_df.shape, jobma_subscription_history_selected_df.shape

((39321, 7), (5562, 11), (11049, 13))

In [8]:
# First: wallet + subscription_history
wallet_sub_outer_df = pd.merge(jobma_wallet_selected_df,
                               jobma_subscription_history_selected_df,
                               on='catcher_id', how='outer')

In [9]:
wallet_sub_outer_df.shape

(11056, 23)

In [10]:
wallet_sub_outer_df.duplicated().sum()

np.int64(866)

In [11]:
wallet_sub_outer_df.drop_duplicates(inplace=True)

In [12]:
wallet_sub_outer_df.isna().sum().sort_values(ascending=False)

credit_amount           9650
sub_user_id             9419
trial_account_type       447
premium_plan_id          122
premium_plan             120
wallet_amount              5
subscription_type          5
updated_at                 5
premium_storage            5
plan_type                  5
is_unlimited               5
billing_cycle_status       5
created_at                 5
subscription_amount        4
subscription_id            4
currency_val               4
credit_given               4
expiry_date                4
currency                   4
status                     4
payment_mode               4
payment_status             4
catcher_id                 0
dtype: int64

In [13]:
# wallet + subscription_history
wallet_sub_inner_df = pd.merge(jobma_wallet_selected_df, jobma_subscription_history_selected_df, on='catcher_id', how='inner')
wallet_sub_inner_df.shape

(11047, 23)

In [14]:
wallet_sub_inner_df

,catcher_id,credit_amount,wallet_amount,subscription_type,plan_type,is_unlimited,premium_storage,trial_account_type,billing_cycle_status,created_at,...,premium_plan_id,premium_plan,subscription_amount,credit_given,expiry_date,currency,currency_val,payment_mode,status,payment_status
0,92,NaN,34.0,0,0,0,0,0.0,0,2017-11-03 12:10:27,...,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",0.0,0,2023-05-22,0,1.0,1,0,0
1,92,NaN,34.0,0,0,0,0,0.0,0,2017-11-03 12:10:27,...,3.0,"{""subscription_charges"":""10000"",""pre_recorded_...",199.0,0,2022-08-12,0,1.0,1,1,1
2,898,NaN,0.0,0,0,0,0,NaN,0,2017-11-03 04:36:27,...,3.0,"{""subscription_charges"":""10000"",""pre_recorded_...",0.0,0,2023-05-22,0,1.0,1,1,0
3,92,NaN,3.0,0,0,0,0,0.0,0,2017-11-03 14:08:57,...,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",0.0,0,2023-05-22,0,1.0,1,0,0
4,92,NaN,3.0,0,0,0,0,0.0,0,2017-11-03 14:08:57,...,3.0,"{""subscription_charges"":""10000"",""pre_recorded_...",199.0,0,2022-08-12,0,1.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11042,9319,NaN,500000.0,0,0,1,0,0.0,1,2024-06-12 11:14:07,...,4.0,"{""subscription_charges"":""10000"",""email_support...",0.0,0,2025-06-18,1,1.0,3,1,1
11043,9365,NaN,137.0,0,0,0,0,0.0,0,2024-07-11 08:05:25,...,2.0,"{""subscription_charges"": ""50"", ""email_support""...",50.0,50,2025-07-11,0,1.0,1,1,1
11044,9405,NaN,500000.0,0,0,1,0,0.0,0,2024-09-04 05:01:02,...,4.0,"{""subscription_charges"":""10000"",""email_support...",0.0,0,2044-12-31,1,1.0,3,1,1
11045,9413,NaN,15000.0,0,0,0,0,0.0,0,2024-09-24 09:18:45,...,3.0,"{""subscription_charges"":""150"",""email_support"":...",150.0,150,2025-09-24,0,1.0,1,1,1
11046,9445,NaN,150.0,0,0,0,0,0.0,0,2025-03-28 05:15:12,...,3.0,"{""subscription_charges"":""150"",""email_support"":...",0.0,150,2035-03-31,0,0.0,3,1,1

In [15]:
#wallet + subscription_history
wallet_sub_left_df = pd.merge(jobma_wallet_selected_df, jobma_subscription_history_selected_df, on='catcher_id', how='left')
wallet_sub_left_df

,catcher_id,credit_amount,wallet_amount,subscription_type,plan_type,is_unlimited,premium_storage,trial_account_type,billing_cycle_status,created_at,...,premium_plan_id,premium_plan,subscription_amount,credit_given,expiry_date,currency,currency_val,payment_mode,status,payment_status
0,669,NaN,0.0,0,0,0,0,NaN,0,2017-11-03 12:10:27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,92,NaN,34.0,0,0,0,0,0.0,0,2017-11-03 12:10:27,...,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",0.0,0.0,2023-05-22,0,1.0,1,0,0
2,92,NaN,34.0,0,0,0,0,0.0,0,2017-11-03 12:10:27,...,3.0,"{""subscription_charges"":""10000"",""pre_recorded_...",199.0,0.0,2022-08-12,0,1.0,1,1,1
3,898,NaN,0.0,0,0,0,0,NaN,0,2017-11-03 04:36:27,...,3.0,"{""subscription_charges"":""10000"",""pre_recorded_...",0.0,0.0,2023-05-22,0,1.0,1,1,0
4,912,NaN,0.0,0,0,0,0,NaN,0,2017-11-03 14:08:57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11046,9319,NaN,500000.0,0,0,1,0,0.0,1,2024-06-12 11:14:07,...,4.0,"{""subscription_charges"":""10000"",""email_support...",0.0,0.0,2025-06-18,1,1.0,3,1,1
11047,9365,NaN,137.0,0,0,0,0,0.0,0,2024-07-11 08:05:25,...,2.0,"{""subscription_charges"": ""50"", ""email_support""...",50.0,50.0,2025-07-11,0,1.0,1,1,1
11048,9405,NaN,500000.0,0,0,1,0,0.0,0,2024-09-04 05:01:02,...,4.0,"{""subscription_charges"":""10000"",""email_support...",0.0,0.0,2044-12-31,1,1.0,3,1,1
11049,9413,NaN,15000.0,0,0,0,0,0.0,0,2024-09-24 09:18:45,...,3.0,"{""subscription_charges"":""150"",""email_support"":...",150.0,150.0,2025-09-24,0,1.0,1,1,1
11050,9445,NaN,150.0,0,0,0,0,0.0,0,2025-03-28 05:15:12,...,3.0,"{""subscription_charges"":""150"",""email_support"":...",0.0,150.0,2035-03-31,0,0.0,3,1,1

In [16]:
wallet_sub_outer_df.isna().sum().sort_values(ascending=False)

credit_amount           9650
sub_user_id             9419
trial_account_type       447
premium_plan_id          122
premium_plan             120
wallet_amount              5
subscription_type          5
updated_at                 5
premium_storage            5
plan_type                  5
is_unlimited               5
billing_cycle_status       5
created_at                 5
subscription_amount        4
subscription_id            4
currency_val               4
credit_given               4
expiry_date                4
currency                   4
status                     4
payment_mode               4
payment_status             4
catcher_id                 0
dtype: int64

In [17]:
wallet_sub_left_df.isna().sum().sort_values(ascending=False)

credit_amount           10367
sub_user_id             10084
trial_account_type        495
premium_plan_id           125
premium_plan              124
expiry_date                 4
subscription_id             4
currency_val                4
payment_mode                4
status                      4
currency                    4
payment_status              4
subscription_amount         4
credit_given                4
catcher_id                  0
premium_storage             0
is_unlimited                0
plan_type                   0
subscription_type           0
wallet_amount               0
created_at                  0
updated_at                  0
billing_cycle_status        0
dtype: int64

In [18]:
wallet_sub_inner_df.isna().sum().sort_values(ascending=False)

credit_amount           10363
sub_user_id             10080
trial_account_type        492
premium_plan_id           121
premium_plan              120
catcher_id                  0
wallet_amount               0
premium_storage             0
is_unlimited                0
plan_type                   0
subscription_type           0
updated_at                  0
created_at                  0
billing_cycle_status        0
subscription_id             0
subscription_amount         0
credit_given                0
expiry_date                 0
currency                    0
currency_val                0
payment_mode                0
status                      0
payment_status              0
dtype: int64

In [19]:
jobma_login_selected_df

,jobma_login_id,jobma_last_login,jobma_created_by,confirmed,jobma_login_status,deleted_at,created_at
0,1,None,None,1,0,NaT,2024-09-26 16:21:36
1,240,2024-10-18 07:38:58,0,1,1,NaT,0000-00-00 00:00:00
2,535,0000-00-00 00:00:00,0,0,1,NaT,2016-11-23 20:53:27
3,642,0000-00-00 00:00:00,1,0,1,NaT,0000-00-00 00:00:00
4,993,0000-00-00 00:00:00,1,1,1,NaT,0000-00-00 00:00:00
...,...,...,...,...,...,...,...
39316,112385,None,None,1,0,NaT,2025-03-26 11:25:35
39317,112387,None,None,1,0,NaT,2025-03-26 11:26:56
39318,112389,2025-03-26 12:57:28,None,1,0,NaT,2025-03-26 11:56:36
39319,112391,None,None,1,0,NaT,2025-03-26 12:58:10
39320,112393,0000-00-00 00:00:00,1,1,0,NaT,2025-03-28 05:15:12

In [20]:
jobma_login_df.T

,0,1,2,3,4,5,6,7,8,9,...,39311,39312,39313,39314,39315,39316,39317,39318,39319,39320
jobma_login_id,1,240,535,642,993,1009,1096,4015,4237,4261,...,112375,112377,112379,112381,112383,112385,112387,112389,112391,112393
jobma_user_name,existinguser@example.com,superadmin@mailinator.com,gaurava@selectsourceintl.com,SMandeep@selectsourceintl.com,ywangb13@gmail.com,teresamcf@gmail.com,hr@3spl.in,krishnak@dtawave.com,aviationindustry@job4u.com,joboportunities@job4u.com,...,pratikabc5@yopmail.com,nayan223@yopmail.com,pratikabc6@yopmail.com,pratikabc7@yopmail.com,pratikabc8@yopmail.com,pratikabc9@yopmail.com,pratikabc10@yopmail.com,ramesh23@yopmail.com,ramesh21@yopmail.com,Sergebrian@yopmail.com
jobma_password,hashedpassword,$2y$10$TyEFO2DlIqVuwnpn1yDRUeRjIklsTP6Rkiq09sn...,$2y$10$WEnjfOt4vTnq/x50aYNaE.zDrr4F00EB37NnnYC...,$2y$10$Lj1NrtAvq0KSPu4VM4/sAOUaq1UCHYf0zo1xbcF...,2982087bec56338d021c81e0bac623a0,76514888624f3db0c43bb828aef91e69,9dccb99534e38083094e4c1a6ff9459f,$2y$10$y9VI/kPvMdvac0Iz.xcvYuQaTVqPMH3rOY6rLMD...,8616b2fac1570dcadd8388e0a21e7f90,8616b2fac1570dcadd8388e0a21e7f90,...,$2b$10$e1C0RgXnmfwGzY39uxzyYuHWUAN/4JvRvAeIWV6...,$2b$10$AfL4D5iXcAtQL5sPbG6g0OFNSP4aJmvStbmx8zp...,$2b$10$.FFYBR0cdqdEou94.YXIeOZdsOFO2I1F0naveE/...,$2b$10$Ph1owj5gGiEX4byahOIetO1HK32kgaVYCYtO6p4...,$2b$10$tecdc/h1iDgC3a4F4fq61OTatR0v8QhRBFnSipn...,$2b$10$VmMPRrRKW61t4mTIWcovr.dguenWGVUEGmYGUOE...,$2b$10$6A5AUWsFx86xHxgYH.eFG.FdyuzcdQrmatTv8IP...,$2b$10$pBYHn72SXg4RULY5rV1L0uhRQOmcueI.g3OZDbm...,$2b$10$tG9Uy9StD4OOPfR7ZeTyR.TLgmrjZSxP5zqWPFp...,$2y$10$p9mNtOk4sjZJU7EMIMiqjeesQf5jvUzvVSYgDNQ...
jobma_role_id,4,1,5,5,4,4,3,5,3,3,...,4,4,4,4,4,4,4,4,4,3
jobma_user_id,1001,162,96,557,908,924,106,117,124,125,...,1126997,1127007,1127067,1127069,1127071,1127089,1127091,1127093,1127095,9445
jobma_last_login,None,2024-10-18 07:38:58,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,2020-02-05 23:09:03,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,...,2025-03-26 07:40:51,None,None,None,None,None,None,2025-03-26 12:57:28,None,0000-00-00 00:00:00
jobma_created_by,None,0,0,1,1,1,0,1,0,0,...,None,None,None,None,None,None,None,None,None,1
confirmed,1,1,0,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
confirmation_code,1,,,,,,,,,,...,1,1,1,1,1,1,1,1,1,
jobma_login_status,0,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
jobma_login_ip,,,,,,,,,,,...,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,172.23.0.1,
forget_password,1,None,0,1,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
remember_token,,N52TQOQ1aR3iA8VVC269FnEFApjJM3M1QqW0BOquGr6cIH...,UBzEkXCpiagAdQiZvHDSMxbu0lQZy3cicuRIf5pFXZWknT...,K5qiDGmZ4UhgBtz94isKfNXo3R01Pi4EJx9AwwyXIrBWjE...,,,,,,,...,,,,,,,,,,
jobma_social_login,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
password_changed_at,2020-10-30 03:57:14,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,2020-05-15 11:50:25,...,2025-03-21 11:58:13,2025-03-21 16:27:57,2025-03-26 16:08:17,2025-03-26 16:12:42,2025-03-26 16:14:49,2025-03-26 16:55:35,2025-03-26 16:56:55,2025-03-26 17:26:35,2025-03-26 18:28:10,2025-03-28 10:45:12
deleted_at,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
created_at,2024-09-26 16:21:36,0000-00-00 00:00:00,2016-11-23 20:53:27,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,0000-00-00 00:00:00,...,2025-03-21 06:28:14,2025-03-21 10:57:58,2025-03-26 10:38:17,2025-03-26 10:42:43,2025-03-26 10:44:49,2025-03-26 11:25:35,2025-03-26 11:26:56,2025-03-26 11:56:36,2025-03-26 12:58:10,2025-03-28 05:15:12
updated_at,2024-09-26 16:21:36,2024-10-18 07:38:58,2017-05-09 18:06:45,2018-02-09 01:02:45,0000-00-00 00:00:00,2020-02-05 23:09:03,2019-11-12 05:35:02,2017-09-20 02:04:49,2019-11-13 05:28:04,2019-11-13 05:28:04,...,2025-03-21 06:28:14,2025-03-21 10:57:58,2025-03-26 10:38:17,2025-03-26 10:42:43,2025-03-26 10:44:49,2025-03-26 11:25:35,2025-03-26 11:26:56,2025-03-26 11:56:36,2025-03-26 12:58:10,2025-03-28 05:15:12
google2fa_secret,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
two_factor_status,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
two_factor_type,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
jobma_login_df['jobma_user_id'].value_counts().head(25)

jobma_user_id
0          470
1115527     35
1115509     19
1115275     15
1115355     11
1116481     11
1115511      8
1114545      8
1113966      8
1115599      7
1115657      6
1115533      6
61658        5
1115659      5
1115361      5
1115877      5
1115491      4
1114233      4
1113549      4
1113848      4
1115493      4
1114237      4
1115225      4
1114567      4
1114915      4
Name: count, dtype: int64

In [22]:
wallet_sub_inner_df

,catcher_id,credit_amount,wallet_amount,subscription_type,plan_type,is_unlimited,premium_storage,trial_account_type,billing_cycle_status,created_at,...,premium_plan_id,premium_plan,subscription_amount,credit_given,expiry_date,currency,currency_val,payment_mode,status,payment_status
0,92,NaN,34.0,0,0,0,0,0.0,0,2017-11-03 12:10:27,...,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",0.0,0,2023-05-22,0,1.0,1,0,0
1,92,NaN,34.0,0,0,0,0,0.0,0,2017-11-03 12:10:27,...,3.0,"{""subscription_charges"":""10000"",""pre_recorded_...",199.0,0,2022-08-12,0,1.0,1,1,1
2,898,NaN,0.0,0,0,0,0,NaN,0,2017-11-03 04:36:27,...,3.0,"{""subscription_charges"":""10000"",""pre_recorded_...",0.0,0,2023-05-22,0,1.0,1,1,0
3,92,NaN,3.0,0,0,0,0,0.0,0,2017-11-03 14:08:57,...,3.0,"{""subscription_charges"": ""10000"", ""pre_recorde...",0.0,0,2023-05-22,0,1.0,1,0,0
4,92,NaN,3.0,0,0,0,0,0.0,0,2017-11-03 14:08:57,...,3.0,"{""subscription_charges"":""10000"",""pre_recorded_...",199.0,0,2022-08-12,0,1.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11042,9319,NaN,500000.0,0,0,1,0,0.0,1,2024-06-12 11:14:07,...,4.0,"{""subscription_charges"":""10000"",""email_support...",0.0,0,2025-06-18,1,1.0,3,1,1
11043,9365,NaN,137.0,0,0,0,0,0.0,0,2024-07-11 08:05:25,...,2.0,"{""subscription_charges"": ""50"", ""email_support""...",50.0,50,2025-07-11,0,1.0,1,1,1
11044,9405,NaN,500000.0,0,0,1,0,0.0,0,2024-09-04 05:01:02,...,4.0,"{""subscription_charges"":""10000"",""email_support...",0.0,0,2044-12-31,1,1.0,3,1,1
11045,9413,NaN,15000.0,0,0,0,0,0.0,0,2024-09-24 09:18:45,...,3.0,"{""subscription_charges"":""150"",""email_support"":...",150.0,150,2025-09-24,0,1.0,1,1,1
11046,9445,NaN,150.0,0,0,0,0,0.0,0,2025-03-28 05:15:12,...,3.0,"{""subscription_charges"":""150"",""email_support"":...",0.0,150,2035-03-31,0,0.0,3,1,1

In [23]:
wallet_sub_inner_df.isna().sum()

catcher_id                  0
credit_amount           10363
wallet_amount               0
subscription_type           0
plan_type                   0
is_unlimited                0
premium_storage             0
trial_account_type        492
billing_cycle_status        0
created_at                  0
updated_at                  0
sub_user_id             10080
subscription_id             0
premium_plan_id           121
premium_plan              120
subscription_amount         0
credit_given                0
expiry_date                 0
currency                    0
currency_val                0
payment_mode                0
status                      0
payment_status              0
dtype: int64

In [24]:
wallet_sub_inner_df['premium_plan_id'].value_counts()

premium_plan_id
3.0     6112
2.0     1743
5.0     1109
6.0      855
4.0      686
7.0      316
1.0       99
8.0        4
10.0       2
Name: count, dtype: int64

In [25]:
wallet_sub_inner_df.to_csv('wallet_sub_inner_df.csv', index=False)