In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/test")

# Catcher

In [2]:
catcher = pd.read_sql("""SELECT jobma_catcher_id, is_premium, subscription_status, company_size, jobma_catcher_parent 
                       FROM jobma_catcher 
                       WHERE jobma_verified IN (1, '1')""", engine).copy()

In [3]:
catcher.isna().sum()

jobma_catcher_id          0
is_premium                0
subscription_status       0
company_size            486
jobma_catcher_parent      0
dtype: int64

In [4]:
catcher.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6116 entries, 0 to 6115
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   jobma_catcher_id      6116 non-null   int64
 1   is_premium            6116 non-null   object
 2   subscription_status   6116 non-null   object
 3   company_size          5630 non-null   object
 4   jobma_catcher_parent  6116 non-null   int64
dtypes: int64(2), object(3)
memory usage: 239.0+ KB

In [5]:
catcher.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6116 entries, 0 to 6115
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   jobma_catcher_id      6116 non-null   int64
 1   is_premium            6116 non-null   object
 2   subscription_status   6116 non-null   object
 3   company_size          5630 non-null   object
 4   jobma_catcher_parent  6116 non-null   int64
dtypes: int64(2), object(3)
memory usage: 239.0+ KB

In [6]:
catcher['is_premium'].value_counts(dropna=False)

is_premium
0    5129
1     986
        1
Name: count, dtype: int64

In [7]:
catcher['subscription_status'].value_counts(dropna=False)

subscription_status
2    3356
1    2751
0       9
Name: count, dtype: int64

In [8]:
catcher['company_size'].value_counts(dropna=False)

company_size
1-25              1927
26-100            1553
101-500           1288
500-1000           688
None               486
More than 1000     174
Name: count, dtype: int64

In [9]:
catcher.replace("", np.nan, inplace=True)
catcher['is_premium'] = pd.to_numeric(catcher['is_premium'], errors='coerce').fillna(0).astype(int)
catcher['subscription_status'] = pd.to_numeric(catcher['subscription_status'], errors='coerce')
catcher['subscription_status'] = catcher['subscription_status'].replace({2: 0}).fillna(0).astype(int)
sub_accounts = catcher['jobma_catcher_parent'].value_counts()
catcher['sub_user'] = catcher['jobma_catcher_id'].map(sub_accounts).fillna(0).astype(int)
mode_val = catcher['company_size'].mode()[0]
catcher['company_size'] = catcher['company_size'].fillna(mode_val)

In [10]:
catcher['is_premium'].value_counts(dropna=False)

is_premium
0    5130
1     986
Name: count, dtype: int64

In [11]:
catcher['subscription_status'].value_counts(dropna=False)

subscription_status
0    3365
1    2751
Name: count, dtype: int64

In [12]:
catcher['company_size'].value_counts(dropna=False)

company_size
1-25              2413
26-100            1553
101-500           1288
500-1000           688
More than 1000     174
Name: count, dtype: int64

# Wallet

In [13]:
wallet = pd.read_sql("SELECT catcher_id AS jobma_catcher_id, wallet_amount, is_unlimited FROM wallet", engine).copy()
wallet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4479 entries, 0 to 4478
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   jobma_catcher_id  4479 non-null   int64
 1   wallet_amount     4479 non-null   float64
 2   is_unlimited      4479 non-null   object
dtypes: float64(1), int64(1), object(1)
memory usage: 105.1+ KB

In [14]:
wallet['wallet_amount'].value_counts(dropna=False).head()

wallet_amount
60.0        3761
50.0         194
500000.0     106
150.0         95
49.0          21
Name: count, dtype: int64

In [15]:
wallet['is_unlimited'].value_counts(dropna=False)

is_unlimited
0    3552
1     846
       81
Name: count, dtype: int64

In [16]:
wallet['wallet_amount'] = pd.to_numeric(wallet['wallet_amount'], errors='coerce').fillna(0)
wallet['wallet_amount'] = np.where(wallet['wallet_amount'] < 0, 0, wallet['wallet_amount'])
wallet['is_unlimited'] = pd.to_numeric(wallet['is_unlimited'], errors='coerce').fillna(0).astype(int)

In [17]:
wallet['is_unlimited'].value_counts(dropna=False)

is_unlimited
0    3633
1     846
Name: count, dtype: int64

In [18]:
wallet

      jobma_catcher_id  wallet_amount  is_unlimited
0                  669           60.0             0
1                  912           60.0             0
2                  135           60.0             0
3                  139           60.0             0
4                  141           60.0             0
...                ...            ...           ...
4474             10529           35.0             0
4475             10530          147.0             0
4476             10531           50.0             0
4477             10533           49.0             0
4478             10536           48.0             0

[4479 rows x 3 columns]

In [19]:
wallet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4479 entries, 0 to 4478
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   jobma_catcher_id  4479 non-null   int64
 1   wallet_amount     4479 non-null   float64
 2   is_unlimited      4479 non-null   int64
dtypes: float64(1), int64(2)
memory usage: 105.1 KB

# Subscription

In [20]:
subscription = pd.read_sql("SELECT catcher_id AS jobma_catcher_id, subscription_amount, currency FROM subscription_history", engine).copy()

In [21]:
subscription.shape

(9493, 3)

In [22]:
subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9493 entries, 0 to 9492
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   jobma_catcher_id     9493 non-null   int64
 1   subscription_amount  9493 non-null   float64
 2   currency             9493 non-null   object
dtypes: float64(1), int64(1), object(1)
memory usage: 222.6+ KB

In [23]:
subscription.tail()

      jobma_catcher_id  subscription_amount currency
9488             10531                100.0        0
9489             10523              25000.0        1
9490             10523              15000.0        1
9491             10533                  0.0        1
9492             10536                  0.0        1

In [24]:
subscription.min()

jobma_catcher_id          135
subscription_amount   -1800.0
currency                    0
dtype: object

In [25]:
subscription.max()

jobma_catcher_id             10536
subscription_amount    99999999.99
currency                         1
dtype: object

In [26]:
subscription['subscription_amount'] = pd.to_numeric(subscription['subscription_amount'], errors='coerce').fillna(0)
subscription['subscription_amount'] = subscription['subscription_amount'].where(subscription['subscription_amount'] > 0, 0)
subscription['subscription_amount'] = np.where(subscription['currency'] == 0,
                                               subscription['subscription_amount'].round(1),
                                               (subscription['subscription_amount'] / 85).round(1))
subscription = subscription.groupby('jobma_catcher_id').agg(subscription_sum=('subscription_amount', 'sum'),
                                                            subscription_count=('jobma_catcher_id', 'count')).reset_index()

In [27]:
subscription.min()

jobma_catcher_id      135.0
subscription_sum        0.0
subscription_count      1.0
dtype: float64

In [28]:
subscription.max()

jobma_catcher_id        10536.0
subscription_sum      1398501.6
subscription_count        116.0
dtype: float64

In [29]:
subscription['subscription_sum'].value_counts(dropna=False).head()

subscription_sum
0.0      417
0.6      319
1.2      248
208.2    247
117.6    207
Name: count, dtype: int64

In [30]:
subscription['subscription_count'].value_counts().head()

subscription_count
1    3038
2     612
3     275
4     158
5      82
Name: count, dtype: int64

In [31]:
subscription[subscription["subscription_count"]==116]

      jobma_catcher_id  subscription_sum  subscription_count
1547              5322           40124.7                 116

In [32]:
subscription.tail(5)

      jobma_catcher_id  subscription_sum  subscription_count
4472             10529               1.2                   1
4473             10530               0.0                   1
4474             10531               1.2                   1
4475             10533               0.0                   1
4476             10536               0.0                   1

# login

In [33]:
login = pd.read_sql("SELECT jobma_user_id AS jobma_catcher_id, jobma_last_login FROM jobma_login", engine)
login

       jobma_catcher_id     jobma_last_login
0                     1  2023-10-16 07:49:26
1                   162  2023-05-29 07:33:47
2                    96  0000-00-00 00:00:00
3                   557  0000-00-00 00:00:00
4                  2656  2024-04-18 11:14:39
...                 ...                  ...
10177            110606                 None
10178            110607                 None
10179            110608                 None
10180            110609                 None
10181            110621                 None

[10182 rows x 2 columns]

In [34]:
# login = pd.read_sql("SELECT jobma_user_id AS jobma_catcher_id, jobma_last_login FROM jobma_login", engine)
login['jobma_last_login'] = pd.to_datetime(login['jobma_last_login'], errors='coerce')
today = pd.to_datetime('2024-06-10 11:24:30')  #Need improvements
login['since_last_login'] = (today - login['jobma_last_login']).dt.days
login = login.groupby('jobma_catcher_id').agg(since_last_login=('since_last_login', 'min')).reset_index()
since_login_filled = login['since_last_login'].fillna(float('inf'))
bins = [0, 30, 90, 180, 365, float('inf')]
labels = [0, 1, 2, 3, 4]
login['since_last_login'] = pd.cut(since_login_filled, bins=bins, labels=labels, right=False)
login

      jobma_catcher_id since_last_login
0                    0                0
1                    1                3
2                    3              NaN
3                    4              NaN
4                    5              NaN
...                ...              ...
9706            110606              NaN
9707            110607              NaN
9708            110608              NaN
9709            110609              NaN
9710            110621              NaN

[9711 rows x 2 columns]

In [35]:
# login['jobma_last_login'] = pd.to_datetime(login['jobma_last_login'], errors='coerce')
# today = pd.to_datetime('2024-06-10 11:24:30')  #Need improvements
# login['since_last_login'] = (today - login['jobma_last_login']).dt.days
# login['since_last_login'] = login['since_last_login'].fillna(np.inf)
# login = login.groupby('jobma_catcher_id').agg(since_last_login=('since_last_login', 'min')).reset_index()
# bins = [0, 30, 90, 180, 365, float('inf')]
# labels = [0, 1, 2, 3, 4]
# login['since_last_login'] = pd.cut(since_login_filled, bins=bins, labels=labels, right=False)

In [36]:
login

      jobma_catcher_id since_last_login
0                    0                0
1                    1                3
2                    3              NaN
3                    4              NaN
4                    5              NaN
...                ...              ...
9706            110606              NaN
9707            110607              NaN
9708            110608              NaN
9709            110609              NaN
9710            110621              NaN

[9711 rows x 2 columns]

In [37]:
login.duplicated().sum()

np.int64(0)

# job_assessment_kit

In [38]:
kit = pd.read_sql("SELECT catcher_id AS jobma_catcher_id FROM job_assessment_kit", engine)
kit

      jobma_catcher_id
0                    0
1                    0
2                    0
3                    0
4                    0
...                ...
5656             10530
5657             10530
5658             10533
5659             10533
5660             10536

[5661 rows x 1 columns]

In [39]:
def clean_pre_recorded_kit_data():
    kitss = pd.read_sql("SELECT catcher_id AS jobma_catcher_id FROM job_assessment_kit", engine)
    return kitss.groupby('jobma_catcher_id').size().reset_index(name='kits_count')
new_kit = clean_pre_recorded_kit_data()
new_kit.sort_values(by= "kits_count", ascending=False)

      jobma_catcher_id  kits_count
784               9095         292
329               5943         197
1051             10121         162
333               5947         151
274               5814         124
...                ...         ...
1188             10529           1
1187             10528           1
1186             10527           1
1184             10525           1
1183             10524           1

[1192 rows x 2 columns]

# Job posting

In [40]:
def clean_job_posting_data():
    postings = pd.read_sql("SELECT jobma_catcher_id FROM jobma_employer_job_posting", engine).copy()
    return postings.groupby('jobma_catcher_id').size().reset_index(name='jobs_posted')
jobs=clean_job_posting_data()
jobs.sort_values(by="jobs_posted", ascending=False)

      jobma_catcher_id  jobs_posted
369               5893          189
757               9095          181
786               9579          179
350               5854          156
680               8497          117
...                ...          ...
5                 2943            1
6                 2947            1
1121             10528            1
1103             10467            1
1100             10457            1

[1127 rows x 2 columns]

# Invitations, live and recorded interview, invite and interview done

In [41]:
invi_df = pd.read_sql("SELECT jobma_catcher_id, jobma_interview_mode, jobma_interview_status FROM jobma_pitcher_invitations", engine)
invi_df.shape

(84848, 3)

In [42]:
invi_df.duplicated().sum()

np.int64(82363)

In [43]:
invi_df['invites_count'] =invi_df['jobma_catcher_id'].map(invi_df['jobma_catcher_id'].value_counts())

In [44]:
invi_df

,jobma_catcher_id,jobma_interview_mode,jobma_interview_status,invites_count
0,2957,1,3,481
1,2957,1,2,481
2,2957,1,3,481
3,2957,1,2,481
4,2957,1,3,481
...,...,...,...,...
84843,9579,1,2,1465
84844,9579,1,2,1465
84845,9579,1,0,1465
84846,9225,1,2,436
84847,9579,1,0,1465

In [45]:
filtered = invi_df[invi_df['jobma_interview_mode'].isin([1, '1'])]
pre_recorded = (filtered.groupby('jobma_catcher_id').size().reset_index(name='pre_recorded'))
pre_recorded.sort_values("pre_recorded", ascending=False)

      jobma_catcher_id  pre_recorded
278               5943          1320
424               6543          1145
315               6014          1136
758               9579           988
345               6139           983
...                ...           ...
1076             10439             1
15                3161             1
13                3159             1
3                 2995             1
175               5505             1

[1116 rows x 2 columns]

In [46]:
def clean_invitations_data():
    invitations = pd.read_sql("SELECT jobma_catcher_id, jobma_interview_mode, jobma_interview_status FROM jobma_pitcher_invitations", engine)
    recorded = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_interview_count')
    live = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_interview_count')
    invites = invitations[invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
    done = invitations[invitations['jobma_interview_status'].isin([1,2,3,4,5,6,7,8,9, '1', '2', '3', '4', '5', '6', '7', '8', '9'])].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
    summary = pd.merge(recorded, live, on='jobma_catcher_id', how='outer')
    summary = pd.merge(summary, invites, on='jobma_catcher_id', how='outer')
    summary = pd.merge(summary, done, on='jobma_catcher_id', how='outer')
    summary.fillna(0, inplace=True)
    return summary

In [47]:
inviteee= clean_invitations_data()

In [48]:
inviteee.sort_values(by='live_interview_count', ascending=False)

,jobma_catcher_id,recorded_interview_count,live_interview_count,invites_count,interview_done
796,9579,988.0,477.0,169.0,1296.0
1009,10056,133.0,113.0,1.0,245.0
985,9994,130.0,111.0,35.0,206.0
47,3678,375.0,109.0,0.0,485.0
1,2957,413.0,68.0,1.0,480.0
...,...,...,...,...,...
1166,10530,3.0,0.0,0.0,3.0
1165,10529,3.0,0.0,0.0,3.0
1164,10528,1.0,0.0,0.0,1.0
1163,10527,10.0,0.0,0.0,10.0
1162,10526,9.0,0.0,4.0,5.0

# New try

In [49]:
df = pd.read_sql("""SELECT jobma_catcher_id,
                    SUM(CASE WHEN jobma_interview_status IN (0, '0') THEN 1 ELSE 0 END) AS invites_count,
                    SUM(CASE WHEN jobma_interview_status NOT IN (0, '0') THEN 1 ELSE 0 END) AS interview_done,
                    SUM(CASE WHEN jobma_interview_mode IN (1, '1') THEN 1 ELSE 0 END) AS recorded_interview_count,
                    SUM(CASE WHEN jobma_interview_mode IN (2, '2') THEN 1 ELSE 0 END) AS live_interview_count
                    FROM 
                        jobma_pitcher_invitations
                    GROUP BY 
                        jobma_catcher_id;""", engine)
df.shape

(1171, 5)

In [50]:
df.sort_values(by='live_interview_count', ascending=False)

,jobma_catcher_id,invites_count,interview_done,recorded_interview_count,live_interview_count
796,9579,169.0,1296.0,988.0,1465.0
308,5943,1.0,1346.0,1321.0,1331.0
460,6543,3.0,1201.0,1145.0,1204.0
349,6014,330.0,842.0,1136.0,1163.0
381,6139,0.0,983.0,983.0,983.0
...,...,...,...,...,...
303,5931,0.0,1.0,0.0,0.0
134,5123,0.0,3.0,3.0,0.0
366,6038,0.0,2.0,1.0,0.0
116,4875,0.0,3.0,0.0,0.0
96,4405,0.0,1.0,1.0,0.0

In [51]:
# def clean_invites_and_interviews(invitations):
#     recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
#     live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
#     invites_only = invitations[invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
#     interview_done = invitations[~invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
#     summary = pd.merge(recorded_inter, live_recorded, on='jobma_catcher_id', how='outer')
#     summary = pd.merge(summary, invites_only, on='jobma_catcher_id', how='outer')
#     summary = pd.merge(summary, interview_done, on='jobma_catcher_id', how='outer')
#     summary.fillna(0, inplace=True)
#     count_cols = ['recorded_int_count', 'live_int_count', 'invites_count', 'interview_done']
#     summary[count_cols] = summary[count_cols].astype(int)
#     return summary
# clean_invites_and_interviews(invitations)

In [52]:
# recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
# recorded_inter.sort_values(by='recorded_int_count', ascending=False).head(10)

# live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
# live_recorded.sort_values(by='live_int_count', ascending=False).head(10)

# invitations['jobma_interview_status'] = pd.to_numeric(invitations['jobma_interview_status'], errors='coerce')
# invitaions_only = invitations[invitations['jobma_interview_status']== 0].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
# invitaions_only.sort_values(by='invites_count', ascending=False).head(10)

# interview_done = invitations[invitations['jobma_interview_status']!= 0].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
# interview_done.sort_values(by='interview_done', ascending=False).head(10)


# #New

# recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
# recorded_inter.sort_values(by='recorded_int_count', ascending=False).head(10)
# live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
# live_recorded.sort_values(by='live_int_count', ascending=False).head(10)

# invitations['jobma_interview_status'] = pd.to_numeric(invitations['jobma_interview_status'], errors='coerce')
# invitaions_only = invitations[invitations['jobma_interview_status']== 0].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
# invitaions_only.sort_values(by='invites_count', ascending=False).head(10)
# interview_done = invitations[invitations['jobma_interview_status']!= 0].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
# interview_done.sort_values(by='interview_done', ascending=False).head(10)