In [1]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/test")

In [2]:
df = pd.read_sql("SELECT jobma_catcher_id, jobma_interview_mode, jobma_interview_status FROM jobma_pitcher_invitations", con=engine)

In [3]:
invitations=df.copy()

In [4]:
def clean_invites_and_interviews(invitations):
    recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
    live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
    invites_only = invitations[invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
    interview_done = invitations[~invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
    summary = pd.merge(recorded_inter, live_recorded, on='jobma_catcher_id', how='outer')
    summary = pd.merge(summary, invites_only, on='jobma_catcher_id', how='outer')
    summary = pd.merge(summary, interview_done, on='jobma_catcher_id', how='outer')
    summary.fillna(0, inplace=True)
    count_cols = ['recorded_int_count', 'live_int_count', 'invites_count', 'interview_done']
    summary[count_cols] = summary[count_cols].astype(int)
    return summary

In [5]:
clean_invites_and_interviews(invitations)

,jobma_catcher_id,recorded_int_count,live_int_count,invites_count,interview_done
0,2656,4,0,0,4
1,2957,413,68,1,480
2,2984,22,6,0,28
3,2995,1,0,0,1
4,3002,1,0,0,1
...,...,...,...,...,...
1166,10530,3,0,0,3
1167,10532,0,2,0,2
1168,10533,2,0,0,2
1169,10534,5,0,0,5
1170,10536,2,0,0,2

In [6]:
recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
recorded_inter.sort_values(by='recorded_int_count', ascending=False).head(10)

     jobma_catcher_id  recorded_int_count
278              5943                1320
424              6543                1145
315              6014                1136
758              9579                 988
345              6139                 983
401              6475                 778
78               4364                 761
252              5874                 754
265              5898                 750
281              5947                 694

In [7]:
live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
live_recorded.sort_values(by='live_int_count', ascending=False).head(10)

     jobma_catcher_id  live_int_count
152              9579             477
198             10056             113
188              9994             111
15               3678             109
0                2957              68
190             10023              64
118              6543              59
212             10121              56
20               4132              46
208             10109              46

In [8]:
invitations['jobma_interview_status'] = pd.to_numeric(invitations['jobma_interview_status'], errors='coerce')
invitaions_only = invitations[invitations['jobma_interview_status']== 0].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
invitaions_only.sort_values(by='invites_count', ascending=False).head(10)

    jobma_catcher_id  invites_count
44             10063          12561
32              9579            169
9               6014            134
13              6184             41
46             10121             40
16              7399             39
38              9994             35
40             10023             30
49             10199             28
55             10300             28

In [9]:
interview_done = invitations[invitations['jobma_interview_status']!= 0].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
interview_done.sort_values(by='interview_done', ascending=False).head(10)

      jobma_catcher_id  interview_done
1014             10063           37485
308               5943            1347
794               9579            1296
460               6543            1201
349               6014            1038
381               6139             983
275               5874             824
437               6475             780
89                4364             761
290               5898             757

In [10]:
recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
recorded_inter.sort_values(by='recorded_int_count', ascending=False).head(10)
live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
live_recorded.sort_values(by='live_int_count', ascending=False).head(10)

invitations['jobma_interview_status'] = pd.to_numeric(invitations['jobma_interview_status'], errors='coerce')
invitaions_only = invitations[invitations['jobma_interview_status']== 0].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
invitaions_only.sort_values(by='invites_count', ascending=False).head(10)
interview_done = invitations[invitations['jobma_interview_status']!= 0].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
interview_done.sort_values(by='interview_done', ascending=False).head(10)

      jobma_catcher_id  interview_done
1014             10063           37485
308               5943            1347
794               9579            1296
460               6543            1201
349               6014            1038
381               6139             983
275               5874             824
437               6475             780
89                4364             761
290               5898             757