In [1]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/test")

In [13]:
# # df = pd.read_sql("SELECT jobma_catcher_id, jobma_interview_mode, jobma_interview_status FROM jobma_pitcher_invitations", con=engine)
df = pd.read_sql("SELECT catcher_id AS jobma_catcher_id, subscription_amount, currency FROM subscription_history", engine).copy()
# subscription=df.copy()

In [14]:
df

      jobma_catcher_id  subscription_amount currency
0                  900                  0.0        0
1                  900                  0.0        0
2                  900                  0.0        0
3                  900                  0.0        0
4                  900                  0.0        0
...                ...                  ...      ...
9488             10531                100.0        0
9489             10523              25000.0        1
9490             10523              15000.0        1
9491             10533                  0.0        1
9492             10536                  0.0        1

[9493 rows x 3 columns]

In [17]:
df[df["jobma_catcher_id"]==900]

   jobma_catcher_id  subscription_amount currency
0               900                  0.0        0
1               900                  0.0        0
2               900                  0.0        0
3               900                  0.0        0
4               900                  0.0        0
5               900                  0.0        0
6               900                  0.0        0
7               900                  0.0        0

In [3]:
# def clean_invites_and_interviews(invitations):
#     recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
#     live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
#     invites_only = invitations[invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
#     interview_done = invitations[~invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
#     summary = pd.merge(recorded_inter, live_recorded, on='jobma_catcher_id', how='outer')
#     summary = pd.merge(summary, invites_only, on='jobma_catcher_id', how='outer')
#     summary = pd.merge(summary, interview_done, on='jobma_catcher_id', how='outer')
#     summary.fillna(0, inplace=True)
#     count_cols = ['recorded_int_count', 'live_int_count', 'invites_count', 'interview_done']
#     summary[count_cols] = summary[count_cols].astype(int)
#     return summary
# clean_invites_and_interviews(invitations)

In [4]:
# recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
# recorded_inter.sort_values(by='recorded_int_count', ascending=False).head(10)

# live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
# live_recorded.sort_values(by='live_int_count', ascending=False).head(10)

# invitations['jobma_interview_status'] = pd.to_numeric(invitations['jobma_interview_status'], errors='coerce')
# invitaions_only = invitations[invitations['jobma_interview_status']== 0].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
# invitaions_only.sort_values(by='invites_count', ascending=False).head(10)

# interview_done = invitations[invitations['jobma_interview_status']!= 0].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
# interview_done.sort_values(by='interview_done', ascending=False).head(10)


# #New

# recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
# recorded_inter.sort_values(by='recorded_int_count', ascending=False).head(10)
# live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
# live_recorded.sort_values(by='live_int_count', ascending=False).head(10)

# invitations['jobma_interview_status'] = pd.to_numeric(invitations['jobma_interview_status'], errors='coerce')
# invitaions_only = invitations[invitations['jobma_interview_status']== 0].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
# invitaions_only.sort_values(by='invites_count', ascending=False).head(10)
# interview_done = invitations[invitations['jobma_interview_status']!= 0].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
# interview_done.sort_values(by='interview_done', ascending=False).head(10)

In [5]:
# subscription['subscription_amount'] = pd.to_numeric(subscription['subscription_amount'], errors='coerce').fillna(0)
# subscription['subscription_amount'] = subscription['subscription_amount'].where(subscription['subscription_amount'] > 0, 0)
# subscription['subscription_amount'] = np.where(subscription['currency'] == 0,subscription['subscription_amount'].round(1),(subscription['subscription_amount'] / 85).round(1))
# subscription = subscription.groupby('jobma_catcher_id').agg(subscription_sum=('subscription_amount', 'sum'),subscription_count=('jobma_catcher_id', 'count')).reset_index()

In [6]:
# subscription.sort_values(by="subscription_count", ascending=False).head(50)

In [7]:
# catcher = pd.read_sql("SELECT jobma_catcher_id, is_premium, subscription_status, company_size, jobma_catcher_parent FROM jobma_catcher WHERE jobma_verified IN (1, '1')", engine).copy()
# df = catcher.copy()
# catcher.replace("", np.nan, inplace=True)
# catcher['is_premium'] = pd.to_numeric(catcher['is_premium'], errors='coerce').fillna(0).astype(int)
# catcher['subscription_status'] = pd.to_numeric(catcher['subscription_status'], errors='coerce')
# catcher['subscription_status'] = catcher['subscription_status'].replace({2: 0}).fillna(0).astype(int)
# sub_accounts = catcher['jobma_catcher_parent'].value_counts()
# catcher['sub_user'] = catcher['jobma_catcher_id'].map(sub_accounts).fillna(0).astype(int)
# mode_val = catcher['company_size'].mode()[0]
# catcher['company_size'] = catcher['company_size'].fillna(mode_val)

In [8]:
# catcher.head(50)

In [9]:
# df.head(50)

In [10]:
# #need attentions here
# login = pd.read_sql("SELECT jobma_user_id AS jobma_catcher_id, jobma_last_login FROM jobma_login", engine)
# df = login.copy()
# login['jobma_last_login'] = pd.to_datetime(login['jobma_last_login'], errors='coerce')
# today = pd.to_datetime('2024-06-10 11:24:30')  #Need improvements
# login['since_last_login'] = (today - login['jobma_last_login']).dt.days
# login = login.groupby('jobma_catcher_id').agg(since_last_login=('since_last_login', 'min')).reset_index()
# since_login_filled = login['since_last_login'].fillna(float('inf'))
# bins = [0, 30, 90, 180, 365, float('inf')]
# labels = [0, 1, 2, 3, 4]
# login['since_last_login'] = pd.cut(since_login_filled, bins=bins, labels=labels, right=False)

In [18]:
# df.duplicated().sum()