In [1]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:Jobma009%40@localhost:3306/test")

# Catcher

In [2]:
catcher = pd.read_sql("""SELECT jobma_catcher_id,is_premium, subscription_status, company_size, jobma_catcher_parent 
                      FROM jobma_catcher
                      WHERE jobma_verified IN (1, '1')""", engine).copy()

In [3]:
catcher

,jobma_catcher_id,is_premium,subscription_status,company_size,jobma_catcher_parent
0,2656,0,1,1-25,0
1,2935,0,2,26-100,0
2,2937,0,2,101-500,0
3,2938,0,1,26-100,0
4,2939,0,2,26-100,0
...,...,...,...,...,...
6111,10532,0,1,1-25,10523
6112,10533,0,1,1-25,0
6113,10534,0,1,1-25,10521
6114,10535,0,1,1-25,9579
6115,10536,0,1,1-25,0

In [4]:
catcher.isna().sum()

jobma_catcher_id          0
is_premium                0
subscription_status       0
company_size            486
jobma_catcher_parent      0
dtype: int64

In [5]:
catcher.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6116 entries, 0 to 6115
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   jobma_catcher_id      6116 non-null   int64
 1   is_premium            6116 non-null   object
 2   subscription_status   6116 non-null   object
 3   company_size          5630 non-null   object
 4   jobma_catcher_parent  6116 non-null   int64
dtypes: int64(2), object(3)
memory usage: 239.0+ KB

In [6]:
catcher.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6116 entries, 0 to 6115
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   jobma_catcher_id      6116 non-null   int64
 1   is_premium            6116 non-null   object
 2   subscription_status   6116 non-null   object
 3   company_size          5630 non-null   object
 4   jobma_catcher_parent  6116 non-null   int64
dtypes: int64(2), object(3)
memory usage: 239.0+ KB

In [7]:
catcher['is_premium'].value_counts(dropna=False)

is_premium
0    5129
1     986
        1
Name: count, dtype: int64

In [8]:
catcher['subscription_status'].value_counts(dropna=False)

subscription_status
2    3356
1    2751
0       9
Name: count, dtype: int64

In [9]:
catcher['company_size'].value_counts(dropna=False)

company_size
1-25              1927
26-100            1553
101-500           1288
500-1000           688
None               486
More than 1000     174
Name: count, dtype: int64

In [10]:
catcher.replace("", np.nan, inplace=True)
catcher['is_premium'] = pd.to_numeric(catcher['is_premium'], errors='coerce').fillna(0).astype(int)
catcher['subscription_status'] = pd.to_numeric(catcher['subscription_status'], errors='coerce')
catcher['subscription_status'] = catcher['subscription_status'].replace({2: 0}).fillna(0).astype(int)
sub_accounts = catcher['jobma_catcher_parent'].value_counts()
catcher['sub_user'] = catcher['jobma_catcher_id'].map(sub_accounts).fillna(0).astype(int)
mode_val = catcher['company_size'].mode()[0]
catcher['company_size'] = catcher['company_size'].fillna(mode_val)

In [11]:
catcher['is_premium'].value_counts(dropna=False)

is_premium
0    5130
1     986
Name: count, dtype: int64

In [12]:
catcher['subscription_status'].value_counts(dropna=False)

subscription_status
0    3365
1    2751
Name: count, dtype: int64

In [13]:
catcher['company_size'].value_counts(dropna=False)

company_size
1-25              2413
26-100            1553
101-500           1288
500-1000           688
More than 1000     174
Name: count, dtype: int64

# Wallet

In [14]:
wallet = pd.read_sql("SELECT catcher_id AS jobma_catcher_id, wallet_amount, is_unlimited FROM wallet", engine).copy()
wallet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4479 entries, 0 to 4478
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   jobma_catcher_id  4479 non-null   int64
 1   wallet_amount     4479 non-null   float64
 2   is_unlimited      4479 non-null   object
dtypes: float64(1), int64(1), object(1)
memory usage: 105.1+ KB

In [15]:
wallet['wallet_amount'].value_counts(dropna=False).head()

wallet_amount
60.0        3761
50.0         194
500000.0     106
150.0         95
49.0          21
Name: count, dtype: int64

In [16]:
wallet['is_unlimited'].value_counts(dropna=False)

is_unlimited
0    3552
1     846
       81
Name: count, dtype: int64

In [17]:
wallet['wallet_amount'] = pd.to_numeric(wallet['wallet_amount'], errors='coerce').fillna(0)
wallet['wallet_amount'] = np.where(wallet['wallet_amount'] < 0, 0, wallet['wallet_amount'])
wallet['is_unlimited'] = pd.to_numeric(wallet['is_unlimited'], errors='coerce').fillna(0).astype(int)

In [18]:
wallet['is_unlimited'].value_counts(dropna=False)

is_unlimited
0    3633
1     846
Name: count, dtype: int64

In [19]:
wallet

      jobma_catcher_id  wallet_amount  is_unlimited
0                  669           60.0             0
1                  912           60.0             0
2                  135           60.0             0
3                  139           60.0             0
4                  141           60.0             0
...                ...            ...           ...
4474             10529           35.0             0
4475             10530          147.0             0
4476             10531           50.0             0
4477             10533           49.0             0
4478             10536           48.0             0

[4479 rows x 3 columns]

In [20]:
wallet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4479 entries, 0 to 4478
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   jobma_catcher_id  4479 non-null   int64
 1   wallet_amount     4479 non-null   float64
 2   is_unlimited      4479 non-null   int64
dtypes: float64(1), int64(2)
memory usage: 105.1 KB

# Subscription

In [21]:
subscription = pd.read_sql("SELECT catcher_id AS jobma_catcher_id, subscription_amount, currency FROM subscription_history", engine).copy()

In [22]:
subscription.head(50)

    jobma_catcher_id  subscription_amount currency
0                900                 0.00        0
1                900                 0.00        0
2                900                 0.00        0
3                900                 0.00        0
4                900                 0.00        0
5                900                 0.00        0
6                900                 0.00        0
7                900                 0.00        0
8                907                 0.00        0
9                907                 0.00        0
10               907                 0.00        0
11               907                 0.00        0
12               135                 0.00        0
13               139                 0.00        0
14               141                 0.00        0
15               144                 0.00        0
16              1020                99.00        0
17              1020                99.00        0
18              1020                99.00        0
19              1020                99.00        0
20              1020                99.00        0
21              1020                99.00        0
22              1020                99.00        0
23              1020                99.00        0
24               907                99.00        0
25              1020                99.00        0
26               907                99.00        0
27              1020                99.00        0
28              2935                53.10        1
29              2936               118.00        1
30              2937               118.00        1
31              2938                 1.18        1
32              2938               199.00        0
33              2939             11800.00        1
34              2940                11.80        1
35              2941             11800.00        1
36              2942                11.80        1
37              2943                11.80        1
38              2944               199.00        0
39              2945               118.00        1
40              2946               100.00        0
41              2947                11.80        1
42              2948               118.00        1
43              2949               118.00        1
44              2949               199.00        0
45              2950               100.00        0
46              2951               118.00        1
47              2952                 1.00        1
48              2953                11.80        1
49              2954             11800.00        1

In [23]:
subscription.min()

jobma_catcher_id          135
subscription_amount   -1800.0
currency                    0
dtype: object

In [24]:
subscription['subscription_amount'] = pd.to_numeric(subscription['subscription_amount'], errors='coerce').fillna(0)
subscription['subscription_amount'] = subscription['subscription_amount'].where(subscription['subscription_amount'] > 0, 0)
subscription['subscription_amount'] = np.where(subscription['currency'] == 0,
                                               subscription['subscription_amount'].round(1),
                                               (subscription['subscription_amount'] / 85).round(1))
subscription = subscription.groupby('jobma_catcher_id').agg(subscription_sum=('subscription_amount', 'sum'),
                                                            subscription_count=('jobma_catcher_id', 'count')).reset_index()

In [25]:
subscription.max()

jobma_catcher_id        10536.0
subscription_sum      1398501.6
subscription_count        116.0
dtype: float64

In [26]:
subscription['subscription_sum'].value_counts(dropna=False).head()

subscription_sum
0.0      417
0.6      319
1.2      248
208.2    247
117.6    207
Name: count, dtype: int64

In [27]:
subscription['subscription_count'].value_counts()

subscription_count
1      3038
2       612
3       275
4       158
5        82
6        77
7        50
8        37
9        29
10       21
11       17
13       13
12       10
15        9
16        8
17        7
14        6
19        4
29        4
25        3
22        2
21        2
24        2
33        1
23        1
18        1
26        1
47        1
116       1
28        1
20        1
27        1
46        1
58        1
Name: count, dtype: int64

In [28]:
subscription.max()

jobma_catcher_id        10536.0
subscription_sum      1398501.6
subscription_count        116.0
dtype: float64

In [29]:
subscription[subscription["subscription_count"]==116]

      jobma_catcher_id  subscription_sum  subscription_count
1547              5322           40124.7                 116

In [30]:
subscription

      jobma_catcher_id  subscription_sum  subscription_count
0                  135               0.0                   1
1                  139               0.0                   1
2                  141               0.0                   1
3                  144               0.0                   1
4                  900               0.0                   8
...                ...               ...                 ...
4472             10529               1.2                   1
4473             10530               0.0                   1
4474             10531               1.2                   1
4475             10533               0.0                   1
4476             10536               0.0                   1

[4477 rows x 3 columns]

 # Login Need improvements

In [31]:
login = pd.read_sql("SELECT jobma_user_id AS jobma_catcher_id, jobma_role_id, jobma_last_login FROM jobma_login", engine)
login

       jobma_catcher_id  jobma_role_id     jobma_last_login
0                     1              4  2023-10-16 07:49:26
1                   162              1  2023-05-29 07:33:47
2                    96              5  0000-00-00 00:00:00
3                   557              5  0000-00-00 00:00:00
4                  2656              3  2024-04-18 11:14:39
...                 ...            ...                  ...
10177            110606              4                 None
10178            110607              4                 None
10179            110608              4                 None
10180            110609              4                 None
10181            110621              4                 None

[10182 rows x 3 columns]

In [32]:
login['jobma_role_id'].value_counts(dropna=False)

jobma_role_id
3    4474
5    2764
4    2463
0     467
9      11
2       2
1       1
Name: count, dtype: int64

In [33]:
4474+2764+2463+467+11+2+1

10182

In [34]:
login['jobma_last_login'].value_counts(dropna=False)

jobma_last_login
0000-00-00 00:00:00    3427
2024-02-20 07:28:20     468
None                    215
2020-06-26 05:09:23       2
2023-11-29 07:56:15       2
                       ...
2024-06-06 10:00:02       1
2024-06-06 10:10:32       1
2024-06-05 05:44:38       1
2024-06-05 23:54:48       1
2023-05-29 07:33:47       1
Name: count, Length: 6071, dtype: int64

In [35]:
login['jobma_last_login'] = pd.to_datetime(login['jobma_last_login'], errors='coerce')

In [36]:
login

       jobma_catcher_id  jobma_role_id    jobma_last_login
0                     1              4 2023-10-16 07:49:26
1                   162              1 2023-05-29 07:33:47
2                    96              5                 NaT
3                   557              5                 NaT
4                  2656              3 2024-04-18 11:14:39
...                 ...            ...                 ...
10177            110606              4                 NaT
10178            110607              4                 NaT
10179            110608              4                 NaT
10180            110609              4                 NaT
10181            110621              4                 NaT

[10182 rows x 3 columns]

# Invitations

In [37]:
invitations = pd.read_sql("SELECT jobma_catcher_id, jobma_interview_mode, jobma_interview_status FROM jobma_pitcher_invitations", engine)

In [38]:
invitations['invites_count'] =invitations['jobma_catcher_id'].map(invitations['jobma_catcher_id'].value_counts())

In [39]:
filtered = invitations[invitations['jobma_interview_mode'].isin([1, '1'])]
pre_recorded = (filtered.groupby('jobma_catcher_id').size().reset_index(name='interview_mode_1_count'))
print(pre_recorded)

      jobma_catcher_id  interview_mode_1_count
0                 2656                       4
1                 2957                     413
2                 2984                      22
3                 2995                       1
4                 3002                       1
...                ...                     ...
1111             10529                       3
1112             10530                       3
1113             10533                       2
1114             10534                       5
1115             10536                       2

[1116 rows x 2 columns]

In [40]:
invitations['recorded_interview_count'] = invitations['jobma_catcher_id'].map(interview_mode['jobma_catcher_id'].value_counts())

NameError: name 'interview_mode' is not defined

In [ ]:
invitations

In [ ]:
ASDFGHJHGFD

In [ ]:
invitations['recorded_interview_count'] = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index()

In [ ]:
recorded = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_interview_count')

In [ ]:
AWESDGFGTERWQW

In [ ]:
recorded.sort_values(by="recorded_interview_count", ascending=False).head(20)

In [ ]:
recorded = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_interview_count')
live = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_interview_count')
invites = invitations[invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
done = invitations[~invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
summary = pd.merge(recorded, live, on='jobma_catcher_id', how='left')
summary = pd.merge(summary, invites, on='jobma_catcher_id', how='left')
summary = pd.merge(summary, done, on='jobma_catcher_id', how='left')
summary.fillna(0, inplace=True)

In [ ]:
# def clean_invites_and_interviews(invitations):
#     recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
#     live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
#     invites_only = invitations[invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
#     interview_done = invitations[~invitations['jobma_interview_status'].isin([0, '0'])].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
#     summary = pd.merge(recorded_inter, live_recorded, on='jobma_catcher_id', how='outer')
#     summary = pd.merge(summary, invites_only, on='jobma_catcher_id', how='outer')
#     summary = pd.merge(summary, interview_done, on='jobma_catcher_id', how='outer')
#     summary.fillna(0, inplace=True)
#     count_cols = ['recorded_int_count', 'live_int_count', 'invites_count', 'interview_done']
#     summary[count_cols] = summary[count_cols].astype(int)
#     return summary
# clean_invites_and_interviews(invitations)

In [ ]:
# recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
# recorded_inter.sort_values(by='recorded_int_count', ascending=False).head(10)

# live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
# live_recorded.sort_values(by='live_int_count', ascending=False).head(10)

# invitations['jobma_interview_status'] = pd.to_numeric(invitations['jobma_interview_status'], errors='coerce')
# invitaions_only = invitations[invitations['jobma_interview_status']== 0].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
# invitaions_only.sort_values(by='invites_count', ascending=False).head(10)

# interview_done = invitations[invitations['jobma_interview_status']!= 0].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
# interview_done.sort_values(by='interview_done', ascending=False).head(10)


# #New

# recorded_inter = invitations[invitations['jobma_interview_mode'].isin([1, '1'])].groupby('jobma_catcher_id').size().reset_index(name='recorded_int_count')
# recorded_inter.sort_values(by='recorded_int_count', ascending=False).head(10)
# live_recorded = invitations[invitations['jobma_interview_mode'].isin([2, '2'])].groupby('jobma_catcher_id').size().reset_index(name='live_int_count')
# live_recorded.sort_values(by='live_int_count', ascending=False).head(10)

# invitations['jobma_interview_status'] = pd.to_numeric(invitations['jobma_interview_status'], errors='coerce')
# invitaions_only = invitations[invitations['jobma_interview_status']== 0].groupby('jobma_catcher_id').size().reset_index(name='invites_count')
# invitaions_only.sort_values(by='invites_count', ascending=False).head(10)
# interview_done = invitations[invitations['jobma_interview_status']!= 0].groupby('jobma_catcher_id').size().reset_index(name='interview_done')
# interview_done.sort_values(by='interview_done', ascending=False).head(10)

In [ ]:
# #need attentions here
# login = pd.read_sql("SELECT jobma_user_id AS jobma_catcher_id, jobma_last_login FROM jobma_login", engine)
# df = login.copy()
# login['jobma_last_login'] = pd.to_datetime(login['jobma_last_login'], errors='coerce')
# today = pd.to_datetime('2024-06-10 11:24:30')  #Need improvements
# login['since_last_login'] = (today - login['jobma_last_login']).dt.days
# login = login.groupby('jobma_catcher_id').agg(since_last_login=('since_last_login', 'min')).reset_index()
# since_login_filled = login['since_last_login'].fillna(float('inf'))
# bins = [0, 30, 90, 180, 365, float('inf')]
# labels = [0, 1, 2, 3, 4]
# login['since_last_login'] = pd.cut(since_login_filled, bins=bins, labels=labels, right=False)

In [ ]:
# df.duplicated().sum()